import { useState } from 'react';
import {cumulativeScopeTotals,type CumulativeReport,type CumulativeScope,type Therapy} from '../../supabase/functions/_shared/cheshire-cumulative.ts';
import { money } from './finance';
import { reportPeriod } from './cumulativeReports';
const labels={insurance_service_cohort:'Insurance reimbursement by service cohort',provider_posted_payments:'Collections by treating provider',facility_reported_activity:'Facility charges & payments'};
const bases={service_date_cohort:'Service-date cohort. Payment posting dates are not established.',payment_posting_date:'Payment-posting dates. These collections are not established service-period revenue.',unresolved_title_filter:'Date basis unresolved: the report title says payment posting, but the filter says service dates.'};
export function CheshireCumulativeReports({reports,scope}:{reports:CumulativeReport[];scope:CumulativeScope}){
 const[therapy,setTherapy]=useState<Therapy|'all'>('all');const[query,setQuery]=useState('');
 if(!reports.length)return null;
 return <div className="ccr-reports"><h3>Year-to-date source reports</h3>{reports.map(report=>{
  const total=cumulativeScopeTotals(report,scope,report.kind==='provider_posted_payments'?'all':therapy);const provider=report.kind==='provider_posted_payments';
  const rows=report.rows.filter(row=>(scope==='all'||row.location===scope)&&(therapy==='all'||row.therapy===therapy));
  const display=provider?report.rows.filter(row=>row.provider!.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.values.total_payments-a.values.total_payments):rows;
  const grouped:Record<string,{therapy:string;values:Record<string,number>}>= {};
  if(!provider)for(const row of rows){const key=`${row.location}:${row.therapy}`;const group=grouped[key]??={therapy:`${row.location} · ${row.therapy}`,values:{}};for(const[key,value]of Object.entries(row.values))group.values[key]=(group.values[key]??0)+value;}
  return <details className="ccr-report" key={report.kind}><summary><span>{labels[report.kind]}</span><strong>{total?money(total.total_payments):'No location attribution'}</strong></summary><div className="ccr-body"><p><strong>{reportPeriod(report)}</strong> · {scope==='all'?'All reported sources':scope}</p><p>{bases[report.period.basis]}</p><p>This is one cumulative report, with no monthly breakdown. Months or days beyond its end date remain missing. The report-generation timestamp was not supplied.</p>{report.warnings.length?<details className="ccr-coverage"><summary>Coverage and source qualifications</summary><ul>{report.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></details>:null}
  {provider&&scope!=='all'?<p className="ccr-notice">Provider collections have no verified location or therapy assignment. Select All locations to review the original provider table.</p>:provider?<><label className="ccr-search">Find provider<input type="search" aria-label="Find provider" value={query} onChange={event=>setQuery(event.target.value)}/></label><p>Compensation and allocated costs are missing, so provider profit is unavailable.</p><div className="ccr-table-wrap"><table><thead><tr><th>Provider</th><th>Insurance</th><th>Patient</th><th>Total collections</th></tr></thead><tbody>{display.map(row=><tr key={`${row.source.sheet}:${row.source.row}`}><th scope="row">{row.provider}</th><td>{money(row.values.insurance_payments)}</td><td>{money(row.values.patient_payments)}</td><td><strong>{money(row.values.total_payments)}</strong></td></tr>)}</tbody></table></div>{display.length===0?<p>No matching provider.</p>:null}</>:<><label className="ccr-search">Therapy<select aria-label={`${labels[report.kind]} therapy`} value={therapy} onChange={event=>setTherapy(event.target.value as Therapy|'all')}><option value="all">All therapies</option>{['OT','PT','ST'].map(value=><option key={value}>{value}</option>)}</select></label><div className="ccr-table-wrap"><table><thead><tr><th>Location · therapy</th>{report.kind==='insurance_service_cohort'?<th>Visits</th>:<th>Charges</th>}<th>Insurance payments</th><th>Patient payments</th><th>Reported payments</th>{report.kind==='insurance_service_cohort'?<th>Per visit</th>:<th>Adjustments</th>}</tr></thead><tbody>{Object.values(grouped).map(group=><tr key={group.therapy}><th scope="row">{group.therapy}</th><td>{report.kind==='insurance_service_cohort'?group.values.visits.toLocaleString('en-US'):money(group.values.charges)}</td><td>{money(group.values.insurance_payments)}</td><td>{money(group.values.patient_payments)}</td><td><strong>{money(group.values.total_payments)}</strong></td><td>{report.kind==='insurance_service_cohort'?(group.values.visits?money(Math.round(group.values.total_payments/group.values.visits)):'—'):money(group.values.total_adjustments)}</td></tr>)}</tbody></table></div>{!Object.keys(grouped).length?<p className="ccr-notice">Need Data: no source row for this location and therapy. This is not a measured zero.</p>:null}{report.kind==='facility_reported_activity'?<details className="ccr-coverage"><summary>Facility-only unposted amounts</summary><p>These source figures are not allocated to therapies and are not labeled accounts receivable.</p><table><tbody>{report.unposted.filter(row=>scope==='all'||row.location===scope).map(row=><tr key={row.location}><th>{row.location}</th><td>{row.value===null?<span className="csd-missing">Need Data</span>:money(row.value)}</td></tr>)}</tbody></table></details>:null}</>}
  <details className="ccr-coverage"><summary>Source and reconciliation</summary><p>{report.source.filename} · {report.source.report_title}</p><p>{report.source.date_label}</p><p>{report.currency_note}</p><p>{report.control_total?'Leaf totals reconcile to the printed source grand total.':'Totals are derived from payer-company leaves; duplicate group subtotals are excluded. There is no printed overall control total.'}</p><p>Original XLS retained in the owner’s private Library, version {report.source.library_version}. Original download and automated recheck are not available in this portal.</p><p className="ccr-hash">SHA-256: {report.source.sha256}</p><p>Source validation: {new Date(report.source.validated_at).toLocaleString('en-US',{timeZone:'UTC'})} UTC. This is not the report-generation time.</p><details><summary>Original rows</summary><ul>{display.map(row=><li key={`${row.source.sheet}:${row.source.row}`}>{provider?row.provider:`${row.location} · ${row.therapy}${row.payer?` · ${row.payer}`:''}`} — {row.source.sheet}!{row.source.range}</li>)}</ul></details></details></div></details>;
 })}</div>;
}
