import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Download,FileUp,LockKeyhole,X} from 'lucide-react';
import {INTAKE_REQUIREMENTS,type SourceType} from './intake';
import {useIntake} from './intakeContext';
import {inspectReportUpload,candidateMapping,recognitionSummary,type ReportInspection,type ConfirmedMapping} from '../../supabase/functions/_shared/cheshire-report-mapping.ts';
import {UPLOAD_TYPES} from '../../supabase/functions/_shared/cheshire-files.ts';
import './report-mapping.css';
const fieldLabel=(field:string)=>field.replaceAll('_',' ');
export function CheshireReportUpload({source,onClose}:{source?:SourceType;onClose:()=>void}){
 const intake=useIntake();const [file,setFile]=useState<File|null>(null);const [kind,setKind]=useState<SourceType|''>(source??'');const [inspection,setInspection]=useState<ReportInspection|null>(null);const [mapping,setMapping]=useState<ConfirmedMapping|null>(null);const [hash,setHash]=useState('');const [noPhi,setNoPhi]=useState(false);const [confirmed,setConfirmed]=useState(false);const [replaces,setReplaces]=useState('');const [inspecting,setInspecting]=useState(false);const [localError,setLocalError]=useState('');const [aiHint,setAiHint]=useState('');const generation=useRef(0);const panel=useRef<HTMLElement|null>(null);const localLock=useRef(false);
 const requirement=INTAKE_REQUIREMENTS.find(item=>item.id===kind);const candidate=inspection?.candidates.find(item=>item.source_type===kind);const fields=[...(requirement?.fields??[]),...(requirement?.optionalFields??[])];const missing=requirement?.fields.filter(field=>!mapping?.columns.includes(field))??[];const duplicates=mapping?.columns.filter((field,index)=>field&&mapping.columns.indexOf(field)!==index)??[];const prior=intake.documents.filter(document=>document.source_type===kind&&document.requested_month===intake.month);
 // The generation counter deliberately invalidates every outstanding inspection on unmount.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const trigger=document.activeElement as HTMLElement|null;panel.current?.focus();return()=>{generation.current++;trigger?.focus?.();};},[]);
 const changeKind=(next:SourceType|'')=>{setKind(next);setConfirmed(false);setReplaces('');setMapping(next&&inspection?candidateMapping(inspection,next,hash):null);};
 const choose=async(next:File|null)=>{
  const current=++generation.current;setFile(next);setInspection(null);setMapping(null);setHash('');setNoPhi(false);setConfirmed(false);setReplaces('');setAiHint('');setLocalError('');if(!next){setInspecting(false);return;}setInspecting(true);
  try{
   if(next.size<1||next.size>5*1024*1024)throw new Error('Choose a non-empty file up to 5 MB.');
   const bytes=await next.arrayBuffer();if(current!==generation.current)return;const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');if(current!==generation.current)return;
   const ext=next.name.toLowerCase().split('.').at(-1)??'';const inspected=inspectReportUpload(new Uint8Array(bytes),next.name,UPLOAD_TYPES[ext]??'');if(current!==generation.current)return;
   setInspection(inspected);setHash(digest);setMapping(kind?candidateMapping(inspected,kind,digest):null);setInspecting(false);
   if(inspected.status==='supported'&&intake.aiEnabled&&intake.mappingEnabled){setAiHint('AI is ranking recognized field codes only…');const hint=await intake.suggestReportType(recognitionSummary(inspected),digest);if(current!==generation.current)return;const labels=hint.source_types.map(type=>INTAKE_REQUIREMENTS.find(item=>item.id===type)?.shortTitle).filter(Boolean);setAiHint(hint.ai_status==='assisted'&&labels.length?`AI report-type hint: ${labels.join(', ')}. Confirm the source meaning below.`:'AI ranking is unavailable. Local suggestions and source checks are still available.');}
  }catch(error){if(current===generation.current)setLocalError(error instanceof Error?error.message:'The file could not be inspected.');}finally{if(current===generation.current)setInspecting(false);}
 };
 const canSubmit=Boolean(file&&kind&&noPhi&&confirmed&&!inspecting&&!localError&&inspection?.status!=='restricted'&&!duplicates.length&&(!mapping||intake.mappingEnabled)&&intake.state==='ready'&&!intake.busy);
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!canSubmit||!file||!kind||localLock.current)return;localLock.current=true;try{if(await intake.upload(file,kind,replaces||null,mapping??undefined))onClose();}finally{localLock.current=false;}};
 const download=()=>{if(!requirement)return;const url=URL.createObjectURL(new Blob([[...requirement.fields,...(requirement.optionalFields??[])].join(',')+'\r\n'],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`${kind}-column-template.csv`;link.click();URL.revokeObjectURL(url);};
 return <div className="cfi-modal-backdrop" onClick={event=>{if(event.target===event.currentTarget&&!intake.busy)onClose();}}><section ref={panel} tabIndex={-1} className="cfi-modal cfi-mapping-modal" role="dialog" aria-modal="true" aria-labelledby="cfi-upload-title" onKeyDown={event=>{if(event.key==='Escape'&&!intake.busy){event.preventDefault();onClose();}if(event.key==='Tab'){const controls=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]')??[]);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}}>
  <header><div><p className="cfd-eyebrow">PRIVATE MONTHLY INTAKE</p><h2 id="cfi-upload-title">Recognize and map a report</h2></div><button aria-label="Close upload" disabled={intake.busy} onClick={onClose}><X size={19}/></button></header>
  <p>Collecting for {intake.month}. Original files stay intact. Only validated, current source data can appear in the dashboard.</p>
  <form onSubmit={submit}>
   <h3>1. Choose the original report</h3><label className="cfi-file-picker"><FileUp size={24}/><strong>{file?.name??'Choose an aggregate business report'}</strong><span>CSV, XLSX, PDF or PNG · up to 5 MB</span><input type="file" accept=".csv,.xlsx,.pdf,.png" aria-label="Choose monthly source file" disabled={intake.busy} onChange={event=>void choose(event.target.files?.[0]??null)}/></label>
   {inspecting?<p role="status">Inspecting the report locally…</p>:null}{localError?<p role="alert">{localError}</p>:null}{inspection?<p className="cfi-scan-note" role="status">{inspection.reason}</p>:null}
   {inspection?.status==='supported'?<div className="cfi-recognition"><strong>Recognized report candidates</strong><ul>{inspection.candidates.filter(item=>item.matched_required>=2).slice(0,3).map(item=><li key={item.source_type}>{INTAKE_REQUIREMENTS.find(r=>r.id===item.source_type)?.shortTitle}: {item.matched_required}/{item.required_count} required field labels recognized</li>)}</ul>{!inspection.candidates.some(item=>item.matched_required>=2)?<p>No clear report type. Select a group and map its columns, or request a supported aggregate export.</p>:null}{aiHint?<p role="status">{aiHint}</p>:null}<small>Recognition is a suggestion, not proof of reporting period, completeness or accounting meaning.</small></div>:null}
   <h3>2. Confirm the report type and columns</h3><label className="cfi-version-label">Dashboard document group<select aria-label="Report type" value={kind} disabled={intake.busy||inspecting} onChange={event=>changeKind(event.target.value as SourceType|'')}><option value="">Choose the report type</option>{INTAKE_REQUIREMENTS.map(item=><option key={item.id} value={item.id}>{item.shortTitle}</option>)}</select></label>
   {requirement?<><p>{requirement.description}</p><p className="cfi-scan-note">{requirement.note}</p></>:null}
   {mapping&&candidate?<div className="cfi-column-map"><p>Source header: row {mapping.header_row}. Map each source column to its actual meaning. Unmapped nonempty columns keep the report incomplete.</p>{candidate.headers.map((header,index)=><label key={index}><span>Column {index+1}: {header.slice(0,100)||'(blank header)'}</span><select aria-label={`Map source column ${index+1}`} disabled={intake.busy} value={mapping.columns[index]} onChange={event=>{const columns=[...mapping.columns];columns[index]=event.target.value;setMapping({...mapping,columns});setConfirmed(false);}}><option value="">Unmapped / needs review</option>{fields.map(field=><option key={field} value={field}>{fieldLabel(field)}{requirement?.fields.includes(field)?' (required)':''}</option>)}</select></label>)}{duplicates.length?<p role="alert">Each dashboard field can be mapped only once: {[...new Set(duplicates)].map(fieldLabel).join(', ')}</p>:null}<div className="cfi-mapping-gaps"><strong>{missing.length?'Missing required fields':'All required field labels are mapped'}</strong>{missing.length?<p>{missing.map(fieldLabel).join(', ')}</p>:<p>Values, periods, scope and totals still need server verification.</p>}<p>Missing values stay unknown. Selecting {intake.month} does not supply the report’s accounting period.</p></div>{inspection?.warnings.map(warning=><p key={warning}>{warning}</p>)}</div>:null}
   {mapping&&!intake.mappingEnabled?<p role="alert">Guided mapping is not available on the private review service yet. Your file has not been uploaded.</p>:null}
   {prior.length?<label className="cfi-version-label">How should this file be used?<select aria-label="Source replacement" value={replaces} disabled={intake.busy} onChange={event=>setReplaces(event.target.value)}><option value="">Add another source file</option>{prior.map(document=><option key={document.id} value={document.id}>Replace {document.file_name}</option>)}</select><small>Replaced originals remain in history. Separate files still need combined reconciliation.</small></label>:null}
   <h3>3. Upload and check</h3><label className="cfi-privacy-check"><input type="checkbox" checked={noPhi} disabled={intake.busy||inspection?.status==='restricted'} onChange={event=>setNoPhi(event.target.checked)}/><span>This is an aggregate business report with no patient/student names, IDs, birth dates, diagnoses, clinical notes or Social Security numbers.</span></label>
   <label className="cfi-privacy-check"><input type="checkbox" aria-label="Confirm report mapping" checked={confirmed} disabled={intake.busy||!kind||!inspection||inspection.status==='restricted'} onChange={event=>setConfirmed(event.target.checked)}/><span>{mapping?'I checked the report type and mapped column meanings. I understand missing or ambiguous data stays incomplete.':'I confirmed the document group. Unsupported layouts will be retained for review and cannot be completed by appearance.'}</span></label>
   <div className="cfi-privacy-note"><LockKeyhole size={16}/><span>Originals stay in private Cheshire storage. AI sees only approved canonical field/check codes and counts, never report headers, names, file contents or financial values.</span></div>
   <button className="cfi-upload-button" type="submit" disabled={!canSubmit}>{intake.busy?'Processing source…':missing.length&&mapping?'Upload with gaps for review':'Upload and check source'}</button>{intake.message?<p className="cfi-message" role="status">{intake.message}</p>:null}
  </form>{requirement?<button className="cfi-template" onClick={download}><Download size={14}/> Download blank column template</button>:null}
 </section></div>;
}
