import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {cheshireSupabase} from '../lib/cheshireSupabase';
import {IntakeContext,type IntakeContextValue} from './intakeContext';
import {isMonth,parseIntakeDocuments,type IntakeDocument,type SourceType} from './intake';
import type {FinanceSnapshot} from './finance';
const MIME:Record<string,string>={csv:'text/csv',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',pdf:'application/pdf',png:'image/png'};
export function CheshireMonthlyIntakeProvider({children}:{children:ReactNode}){
 const [month,changeMonth]=useState(new Date().toISOString().slice(0,7));const [selected,setSelected]=useState<SourceType>('coverage_manifest');const [documents,setDocuments]=useState<IntakeDocument[]>([]);const [referenceSnapshot,changeReferenceSnapshot]=useState<FinanceSnapshot|null>(null);const [state,setState]=useState<IntakeContextValue['state']>('checking');const [aiEnabled,setAiEnabled]=useState(false);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [attempt,setAttempt]=useState(0);const epoch=useRef(0);const actor=useRef<string|null>(null);
 const refresh=useCallback(()=>setAttempt(value=>value+1),[]);
 const setMonth=useCallback((value:string)=>{if(!isMonth(value)||value===month)return;epoch.current++;setDocuments([]);setMessage('');setState('checking');changeMonth(value);},[month]);
 const setReferenceSnapshot=useCallback((snapshot:FinanceSnapshot|null,ownerId:string|null)=>{if(!snapshot||ownerId===actor.current)changeReferenceSnapshot(snapshot);},[]);
 useEffect(()=>{let active=true;let started=false;const load=async(userId:string,version:number)=>{const current=()=>active&&epoch.current===version;try{
   const [rows,capability]=await Promise.all([cheshireSupabase.from('cheshire_intake_document').select('id,source_type,requested_month,reported_month,file_name,content_sha256,status,created_at,reviewed_at,source_origin,storage_path,validation,failure_message,supersedes_id,validation_dependencies,source_period_label,source_scope_label,figure_unlocked').or(`requested_month.eq.${month}-01,source_origin.eq.existing_source`).order('created_at',{ascending:false}).limit(250),cheshireSupabase.functions.invoke('cheshire-intake-review',{body:{operation:'capabilities'}})]);
   if(!current()||actor.current!==userId)return;if(rows.error||capability.error||!capability.data?.uploads_enabled||(rows.data?.length??0)>=250){setState('unavailable');setMessage('Private monthly uploads are not available yet. Existing financial sources remain visible.');return;}
   setDocuments(parseIntakeDocuments(rows.data??[]));setAiEnabled(Boolean(capability.data.ai_enabled));setState('ready');
  }catch{if(current()){setState('unavailable');setMessage('The monthly checklist could not be loaded. Refresh to try again.');}}};
  const activate=(userId:string|null)=>{if(!active)return;started=true;const version=++epoch.current;const changed=actor.current!==userId;actor.current=userId;setDocuments([]);if(changed)setMessage('');setBusy(false);setState(userId?'checking':'no-access');if(changed)changeReferenceSnapshot(null);if(userId)setTimeout(()=>void load(userId,version),0);};
  const {data:listener}=cheshireSupabase.auth.onAuthStateChange((event,session)=>{if(event==='TOKEN_REFRESHED'&&actor.current===session?.user.id)return;activate(session?.user.id??null);});
  void cheshireSupabase.auth.getSession().then(({data})=>{if(!started)activate(data.session?.user.id??null);});
  // The epoch is a request-generation counter, not a DOM ref; cleanup intentionally invalidates the latest generation.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  return()=>{active=false;epoch.current++;listener.subscription.unsubscribe();};
 },[month,attempt]);
 const invoke=async(body:Record<string,unknown>,token:string)=>{const {data,error}=await cheshireSupabase.functions.invoke('cheshire-intake-review',{body,headers:{Authorization:`Bearer ${token}`}});if(error||data?.error){let detail=data?.error;if(!detail&&error&&'context' in error){try{detail=(await (error.context as Response).json())?.error;}catch{/* no raw response in the UI */}}throw new Error(typeof detail==='string'?detail:'The private intake service could not finish. Please retry.');}return data;};
 const upload=async(file:File,source:SourceType,replaces:string|null)=>{const version=epoch.current,userId=actor.current;const current=()=>epoch.current===version&&actor.current===userId;if(!userId||state!=='ready'||busy)return false;const extension=file.name.toLowerCase().split('.').at(-1)??'';if(!MIME[extension]||file.size<1||file.size>5*1024*1024){setMessage('Choose a non-empty CSV, XLSX, PDF or PNG file up to 5 MB.');return false;}setBusy(true);setMessage('Preparing your private upload…');
  try{const sessionResult=await cheshireSupabase.auth.getSession();if(!current()||sessionResult.data.session?.user.id!==userId)return false;const token=sessionResult.data.session.access_token;const bytes=await file.arrayBuffer();if(!current())return false;const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');if(!current())return false;
   const prepared=await invoke({operation:'prepare',source_type:source,requested_month:month,file_name:file.name,content_sha256:hash,byte_size:file.size,mime_type:MIME[extension],contains_no_phi:true,supersedes_id:replaces},token);if(!current())return false;
   if(prepared.upload_required){if(typeof prepared.storage_path!=='string'||!prepared.storage_path.startsWith(`${userId}/`))throw new Error('The upload reservation does not belong to this account.');setMessage('Uploading to private Cheshire storage…');const uploaded=await cheshireSupabase.storage.from('cheshire-intake').upload(prepared.storage_path,file,{contentType:MIME[extension],upsert:false,cacheControl:'0',headers:{Authorization:`Bearer ${token}`}});if(!current())return false;if(uploaded.error&&!(String(uploaded.error.message).toLowerCase().includes('already exists')||String(uploaded.error.message).toLowerCase().includes('duplicate')))throw new Error('The file upload did not finish. Retry the same file to resume safely.');}
   setMessage('File received. Checking its period, fields, coverage and totals…');const reviewed=await invoke({operation:'review',document_id:prepared.document.id,expected_sha256:hash},token);if(!current())return false;setMessage(reviewed.review_in_progress?'Your file is received. Its review is still running; refresh this source shortly.':'Upload received and source check finished. Review the findings below.');refresh();return true;
  }catch(error){if(current())setMessage(error instanceof Error?error.message:'The upload could not finish.');return false;}finally{if(current())setBusy(false);}};
 const review=async(document:IntakeDocument)=>{const version=epoch.current,userId=actor.current;if(state!=='ready'||busy)return;setBusy(true);setMessage('Rechecking the saved source version…');try{const sessionResult=await cheshireSupabase.auth.getSession();if(epoch.current!==version||sessionResult.data.session?.user.id!==userId)return;await invoke({operation:'review',document_id:document.id,expected_sha256:document.content_sha256},sessionResult.data.session.access_token);if(epoch.current===version){setMessage('Source check finished.');refresh();}}catch(error){if(epoch.current===version)setMessage(error instanceof Error?error.message:'The review could not finish.');}finally{if(epoch.current===version)setBusy(false);}};
 return <IntakeContext.Provider key={actor.current??'signed-out'} value={{month,setMonth,selected,setSelected,documents,referenceSnapshot,setReferenceSnapshot,state,aiEnabled,message,busy,refresh,upload,review}}>{children}</IntakeContext.Provider>;
}
