import { MAX_PAYER_LENGTH } from '../../supabase/functions/_shared/cheshire-intake.ts';
import { METRICS, BASES, NORMALIZER_VERSION, type MetricResponse, type SourceMetric } from '../../supabase/functions/_shared/cheshire-metrics.ts';
import { SOURCE_TYPES, isMonth } from './intake.ts';
import { LOCATIONS } from './finance.ts';
export type { MetricResponse, SourceMetric };
export const BASIS_LABELS:Record<string,string>={payment_date:'Payment-date attribution',service_date:'Service-date attribution',report_as_of:'Report-as-of basis',invoice_reported_month:'Invoice reporting month; not cash receipts',program_reported_month:'Program reporting month; receipt timing unconfirmed',payroll_reported_month:'Payroll reporting month; cost-period matching still needed',expense_reported_month:'Expense reporting month',overhead_reported_month:'Uploaded monthly cost source'};
export function parseMetricResponse(input:unknown,month:string,location:string):MetricResponse {
 if(!input||typeof input!=='object')throw new Error('Invalid metric response');const result=input as MetricResponse;
 if(!isMonth(result.month)||result.month!==month||result.location!==location||!Array.isArray(result.sources)||result.sources.length>7||!Array.isArray(result.blocked)||result.blocked.length>7||result.profit?.available!==false||typeof result.profit.reason!=='string'||typeof result.accounting_request!=='string')throw new Error('Invalid metric scope');
 const sources=new Set<string>();for(const source of result.sources){if(!SOURCE_TYPES.includes(source.source_type)||sources.has(source.source_type)||source.coverage!=='validated_source_scope'||typeof source.document_id!=='string'||!/^[a-f0-9]{64}$/.test(source.content_sha256)||source.validator_version!=='cheshire-intake-v1'||source.normalizer_version!==NORMALIZER_VERSION||!Array.isArray(source.location_coverage)||source.location_coverage.some(name=>!LOCATIONS.includes(name as never))||!Array.isArray(source.metrics)||source.metrics.length>32)throw new Error('Invalid source metrics');sources.add(source.source_type);const keys=new Set<string>();for(const metric of source.metrics){const definition=METRICS[metric.key];const key=`${metric.key}:${metric.basis}`;if(!definition||keys.has(key)||metric.label!==definition.label||metric.unit!==definition.unit||metric.scale!==definition.scale||!Number.isSafeInteger(metric.value)||(metric.value<0&&metric.key!=='adjustments')||!BASES.includes(metric.basis)||metric.location!==(location==='all'?null:location)||!Array.isArray(metric.source_locations)||metric.source_locations.some(name=>!LOCATIONS.includes(name as never))||new Set(metric.source_locations).size!==metric.source_locations.length||(location!=='all'&&metric.source_locations.some(name=>name!==location))||!Number.isSafeInteger(metric.source_rows)||metric.source_rows<1)throw new Error('Invalid metric value');if(source.source_type==='insurance_revenue'){
 const payers=metric.payer_breakdown;if(!Array.isArray(payers)||!payers.length||payers.length>100)throw new Error('Missing payer coverage');const names=new Set<string>();const locations=new Set<string>();let value=0,rows=0;for(const payer of payers){if(typeof payer.payer!=='string'||!payer.payer.trim()||payer.payer.length>MAX_PAYER_LENGTH||names.has(payer.payer)||!Number.isSafeInteger(payer.value)||(payer.value<0&&metric.key!=='adjustments')||!Number.isSafeInteger(payer.source_rows)||payer.source_rows<1||!Array.isArray(payer.source_locations)||!payer.source_locations.length||new Set(payer.source_locations).size!==payer.source_locations.length||payer.source_locations.some(location=>!metric.source_locations.includes(location)))throw new Error('Invalid payer subtotal');names.add(payer.payer);payer.source_locations.forEach(location=>locations.add(location));value+=payer.value;rows+=payer.source_rows;}if(!Number.isSafeInteger(value)||value!==metric.value||rows!==metric.source_rows||locations.size!==metric.source_locations.length)throw new Error('Payer subtotals do not reconcile');
 }else if(metric.payer_breakdown!==undefined)throw new Error('Unexpected payer breakdown');
 keys.add(key);}}
 if(result.blocked.some(block=>!SOURCE_TYPES.includes(block.source_type)||typeof block.reason!=='string'||block.reason.length>1000))throw new Error('Invalid metric finding');return result;
}
export function formatMetric(metric:SourceMetric){return metric.unit==='USD'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(metric.value/metric.scale):`${new Intl.NumberFormat('en-US',{maximumFractionDigits:4}).format(metric.value/metric.scale)} ${metric.unit}`;}
