import {MAPPING_VERSION,parseMappedUpload,validateMapping,mappingFromProvenance,validateRecognitionSummary,type MappingProvenance} from './cheshire-report-mapping.ts';
import { INTAKE_LOCATIONS } from './cheshire-intake.ts';
import { NORMALIZER_VERSION, normalizeMetrics, normalizationIssue, dependencyRevision, serveMetrics, type MetricDocument } from './cheshire-metrics.ts';
import { SOURCE_TYPES, REQUIRED_CHECKS, isMonth, validateTable, reviewFixedBaseline, sanitizedAiSummary, type SourceType, type ReviewResult, type ValidationContext } from './cheshire-intake.ts';
import { MAX_UPLOAD_BYTES, UPLOAD_TYPES, uploadExtension, parseUpload } from './cheshire-files.ts';
export type IntakeEnvironment={SUPABASE_URL:string;SUPABASE_SERVICE_ROLE_KEY:string;HF_TOKEN?:string};
type Fetcher=typeof fetch;
type DocumentRow={id:string;source_type:SourceType;requested_month:string|null;reported_month:string|null;uploaded_by:string|null;file_name:string;content_sha256:string;byte_size:number|null;mime_type:string|null;storage_path:string|null;source_origin:string;status:string;validation:ReviewResult|null;validation_scope:Record<string,unknown>|null;validation_dependencies:Record<string,string>|null;review_started_at:string|null;[key:string]:unknown};
class IntakeError extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code;}}
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const HASH=/^[a-f0-9]{64}$/;
const origins=new Set(['https://www.thrivoli.com','https://thrivoli.com','https://thrivoli.vercel.app','https://thrivoli-briantraudts-projects.vercel.app']);
function allowedOrigin(origin:string|null){return !origin||origins.has(origin)||/^https:\/\/thrivoli-[a-z0-9-]+-briantraudts-projects\.vercel\.app$/.test(origin);}
function response(request:Request,body:unknown,status=200){const origin=request.headers.get('origin');const headers:Record<string,string>={'Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin'};if(origin&&allowedOrigin(origin)){headers['Access-Control-Allow-Origin']=origin;headers['Access-Control-Allow-Headers']='authorization,apikey,content-type,x-client-info';headers['Access-Control-Allow-Methods']='POST, OPTIONS';}return new Response(JSON.stringify(body),{status,headers});}
function safeDocument(row:DocumentRow){const {validation_scope,review_token,uploaded_by,...safe}=row;void validation_scope;void review_token;void uploaded_by;return safe;}
export async function sha256(bytes:Uint8Array){const buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;return [...new Uint8Array(await crypto.subtle.digest('SHA-256',buffer))].map(value=>value.toString(16).padStart(2,'0')).join('');}
async function readBounded(result:{headers:Headers;body:ReadableStream<Uint8Array>|null},limit=MAX_UPLOAD_BYTES){if(Number(result.headers.get('content-length')??0)>limit)throw new IntakeError(422,'file_size','The stored file exceeds the 5 MB review limit.');const reader=result.body?.getReader();if(!reader)throw new IntakeError(422,'empty_file','The stored file is empty.');const chunks:Uint8Array[]=[];let size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>limit){await reader.cancel();throw new IntakeError(422,'file_size','The stored file exceeds the review limit.');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return bytes;}
function database(environment:IntakeEnvironment,fetcher:Fetcher){const url=environment.SUPABASE_URL.replace(/\/$/,'');return async(path:string,init:RequestInit={})=>{const result=await fetcher(`${url}/rest/v1/${path}`,{...init,signal:AbortSignal.timeout(15000),headers:{apikey:environment.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${environment.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:'return=representation',...(init.headers??{})}});const data=await result.json().catch(()=>null);if(!result.ok)throw new IntakeError(result.status===409?409:503,'database_unavailable','The private intake record could not be saved. Retry without changing the file.');return data;};}
function complete(row:DocumentRow,month:string){return row.status==='complete'&&row.requested_month===`${month}-01`&&row.reported_month===`${month}-01`&&row.validation?.status==='complete'&&row.validation.validator_version==='cheshire-intake-v1'&&row.validation.missing_items.length===0&&REQUIRED_CHECKS.every(key=>row.validation!.checks.some(check=>check.key===key&&check.passed));}
function reviewWithoutExtraction(message:string):ReviewResult{return{validator_version:'cheshire-intake-v1',status:'incomplete',reported_month:null,checks:REQUIRED_CHECKS.map(key=>({key,passed:false,message:key==='document_type'?message:'A supported aggregate table is required before this check can run.'})),missing_items:[message],row_count:0,covered_locations:[],canonical_fields:[],ai_status:'not_requested'};}
export async function handleIntake(request:Request,environment:IntakeEnvironment,fetcher:Fetcher=fetch):Promise<Response>{
 if(!allowedOrigin(request.headers.get('origin')))return response(request,{error:'This origin is not allowed.'},403);
 if(request.method==='OPTIONS')return response(request,{ok:true});
 if(request.method!=='POST')return response(request,{error:'Method not allowed.'},405);
 const authorization=request.headers.get('authorization')??'';
 if(!authorization.startsWith('Bearer ')||authorization.length>16384)return response(request,{error:'Sign in to the Cheshire portal.'},401);
 if(!environment.SUPABASE_URL||!environment.SUPABASE_SERVICE_ROLE_KEY)return response(request,{error:'Private intake is not configured yet.'},503);
 const db=database(environment,fetcher);let reviewing:DocumentRow|null=null;let reviewToken:string|null=null;
 try{
  const auth=await fetcher(`${environment.SUPABASE_URL.replace(/\/$/,'')}/auth/v1/user`,{headers:{Authorization:authorization,apikey:environment.SUPABASE_SERVICE_ROLE_KEY},signal:AbortSignal.timeout(10000)});
  if(!auth.ok)throw new IntakeError(401,'invalid_session','Your sign-in session could not be verified.');
  const user=await auth.json();if(!UUID.test(user?.id??'')||typeof user.email!=='string'||!user.email_confirmed_at)throw new IntakeError(401,'unconfirmed_session','A confirmed account is required.');
  const [reader,portal]=await Promise.all([db(`cheshire_finance_reader?select=user_id&user_id=eq.${encodeURIComponent(user.id)}`),db(`cheshire_portal_member?select=email&email=eq.${encodeURIComponent(user.email.toLowerCase())}`)]);
  if(!Array.isArray(reader)||reader.length!==1||!Array.isArray(portal)||portal.length!==1)throw new IntakeError(403,'not_authorized','Financial document access is not enabled for this account.');
  if(Number(request.headers.get('content-length')??0)>16000)throw new IntakeError(413,'request_size','Send file metadata only; upload the file directly to private storage.');
  const rawBody=new TextDecoder('utf-8',{fatal:true}).decode(await readBounded(request,16000));if(rawBody.length>16000)throw new IntakeError(413,'request_size','The metadata request is too large.');
  let body:Record<string,unknown>;try{body=JSON.parse(rawBody);}catch{throw new IntakeError(400,'invalid_json','Send a valid metadata request.');}if(!body||typeof body!=='object'||Array.isArray(body))throw new IntakeError(400,'invalid_request','Invalid metadata request.');
  if(body.operation==='metrics'){
   if(Object.keys(body).some(key=>!['operation','month','location'].includes(key))||!isMonth(body.month)||(body.location!==undefined&&body.location!=='all'&&!INTAKE_LOCATIONS.includes(body.location as never)))throw new IntakeError(400,'invalid_metric_scope','Choose a valid month and reporting location.');
   const state=await db('rpc/read_cheshire_metric_state',{method:'POST',body:JSON.stringify({p_month:`${body.month}-01`})});
   return response(request,{metrics:serveMetrics(state,body.month,typeof body.location==='string'?body.location:'all')});
  }
  let aiConfiguration={ai_enabled:false,ai_monthly_limit:10};try{const settings=await db('cheshire_intake_settings?id=eq.true&select=ai_enabled,ai_monthly_limit&limit=1');if(settings.length===1&&settings[0].ai_enabled===true&&Number.isInteger(settings[0].ai_monthly_limit)&&settings[0].ai_monthly_limit>=1&&settings[0].ai_monthly_limit<=10)aiConfiguration=settings[0];}catch{/* AI configuration failure must not prevent source validation. */}
  if(body.operation==='capabilities')return response(request,{uploads_enabled:true,accepted_types:Object.keys(UPLOAD_TYPES),max_bytes:MAX_UPLOAD_BYTES,ai_enabled:aiConfiguration.ai_enabled&&Boolean(environment.HF_TOKEN),validator_version:'cheshire-intake-v1',mapping_version:MAPPING_VERSION});
  if(body.operation==='recognize'){
   if(Object.keys(body).some(key=>!['operation','content_sha256','summary'].includes(key))||typeof body.content_sha256!=='string'||!HASH.test(body.content_sha256))throw new IntakeError(400,'invalid_recognition','Send only a verified source hash and canonical recognition summary.');
   let summary;try{summary=validateRecognitionSummary(body.summary);}catch(error){throw new IntakeError(400,'invalid_recognition',error instanceof Error?error.message:'Invalid recognition summary.');}
   if(!summary.candidate_source_types.length||!aiConfiguration.ai_enabled||!environment.HF_TOKEN)return response(request,{source_types:[],ai_status:'unavailable'});
   const key=await sha256(new TextEncoder().encode('recognition:'+MAPPING_VERSION+':'+body.content_sha256+':'+JSON.stringify(summary)));
   let reserved=false;try{reserved=await db('rpc/reserve_cheshire_intake_ai_call',{method:'POST',body:JSON.stringify({p_cache_key:key,p_limit:aiConfiguration.ai_monthly_limit})});}catch{/* A budget failure must not block local mapping. */}
   if(reserved!==true)return response(request,{source_types:[],ai_status:'unavailable'});
   try{
    const ai=await fetcher('https://router.huggingface.co/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${environment.HF_TOKEN}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(20000),body:JSON.stringify({model:'openai/gpt-oss-120b:cerebras',messages:[{role:'system',content:'Rank likely report source types using canonical field codes only. Return JSON with exactly source_types, a unique array containing only supplied candidate_source_types. No prose, values, completion decisions or new mappings. A human will confirm the report type and columns.'},{role:'user',content:JSON.stringify(summary)}],max_tokens:256,temperature:0,reasoning_effort:'low'})});
    if(!ai.ok)throw new Error('AI unavailable');const payload=await ai.json();const content=payload?.choices?.[0]?.message?.content;if(typeof content!=='string'||content.length>2000)throw new Error('Invalid AI response');const result=JSON.parse(content);
    if(!result||typeof result!=='object'||Array.isArray(result)||Object.keys(result).some(key=>key!=='source_types')||!Array.isArray(result.source_types)||result.source_types.length>summary.candidate_source_types.length||result.source_types.some((kind:unknown)=>!summary.candidate_source_types.includes(kind as SourceType))||new Set(result.source_types).size!==result.source_types.length)throw new Error('Invalid AI response');
    return response(request,{source_types:result.source_types,ai_status:'assisted'});
   }catch{return response(request,{source_types:[],ai_status:'unavailable'});}
  }
  if(body.operation==='prepare'){
   const allowed=['operation','source_type','requested_month','file_name','content_sha256','byte_size','mime_type','contains_no_phi','supersedes_id'];if(Object.keys(body).some(key=>!allowed.includes(key)))throw new IntakeError(400,'unexpected_fields','Client-authored paths or review status are not accepted.');
   if(!SOURCE_TYPES.includes(body.source_type as SourceType)||!isMonth(body.requested_month)||typeof body.file_name!=='string'||body.file_name.length<1||body.file_name.length>160||(/[\\/]/.test(body.file_name)||[...body.file_name].some(character=>character.charCodeAt(0)<32))||typeof body.content_sha256!=='string'||!HASH.test(body.content_sha256)||!Number.isInteger(body.byte_size)||Number(body.byte_size)<1||Number(body.byte_size)>MAX_UPLOAD_BYTES||body.contains_no_phi!==true)throw new IntakeError(400,'invalid_metadata','Choose a source type and month, a valid file up to 5 MB, and confirm that patient/student details are excluded.');
   let extension:string;try{extension=uploadExtension(body.file_name);}catch{throw new IntakeError(400,'file_type','Upload CSV, XLSX, PDF or PNG only.');}if(body.mime_type!==UPLOAD_TYPES[extension])throw new IntakeError(400,'file_type','The file media type does not match its extension.');
   if(body.supersedes_id!==undefined&&body.supersedes_id!==null&&(typeof body.supersedes_id!=='string'||!UUID.test(body.supersedes_id)))throw new IntakeError(400,'invalid_version','Choose a valid prior source version.');
   const period=`${body.requested_month}-01`;if(body.supersedes_id){const prior=await db(`cheshire_intake_document?id=eq.${body.supersedes_id}&source_type=eq.${body.source_type}&requested_month=eq.${period}&limit=1`);if(prior.length!==1)throw new IntakeError(400,'invalid_version','A replacement must reference the same document group and reporting month.');}const filter=`source_type=eq.${body.source_type}&requested_month=eq.${period}&content_sha256=eq.${body.content_sha256}`;
   const existing=await db(`cheshire_intake_document?${filter}&limit=1`) as DocumentRow[];
   if(existing.length){const document=existing[0];if(document.status==='uploading'&&document.uploaded_by!==user.id)throw new IntakeError(409,'other_upload_pending','An identical upload is already reserved by another approved account. Ask that uploader to finish it; no source will be overwritten.');return response(request,{document:safeDocument(document),upload_required:document.status==='uploading',storage_path:document.status==='uploading'?document.storage_path:null,reused:true});}
   const start=new Date();start.setUTCDate(1);start.setUTCHours(0,0,0,0);const recent=await db(`cheshire_intake_document?select=id&source_origin=eq.portal_upload&created_at=gte.${encodeURIComponent(start.toISOString())}&limit=100`);if(recent.length>=100)throw new IntakeError(429,'monthly_upload_limit','The monthly upload safety limit has been reached. Contact the workspace owner.');
   const id=crypto.randomUUID(),path=`${user.id}/${id}/source.${extension}`;
   let created:DocumentRow[];
   try{created=await db('cheshire_intake_document',{method:'POST',body:JSON.stringify({id,source_type:body.source_type,requested_month:period,uploaded_by:user.id,file_name:body.file_name,content_sha256:body.content_sha256,byte_size:body.byte_size,mime_type:body.mime_type,storage_path:path,source_origin:'portal_upload',status:'uploading',supersedes_id:body.supersedes_id??null,no_phi_attested_at:new Date().toISOString()})});}
   catch(error){if(error instanceof IntakeError&&error.status===409)throw new IntakeError(409,'duplicate_race','This upload was just reserved. Retry to reuse the existing document.');throw error;}
   return response(request,{document:safeDocument(created[0]),upload_required:true,storage_path:path,reused:false});
  }
  if(body.operation!=='review'||Object.keys(body).some(key=>!['operation','document_id','expected_sha256','mapping'].includes(key))||typeof body.document_id!=='string'||!UUID.test(body.document_id)||typeof body.expected_sha256!=='string'||!HASH.test(body.expected_sha256))throw new IntakeError(400,'invalid_review','Choose a saved document version to review.');
  const found=await db(`cheshire_intake_document?id=eq.${body.document_id}&content_sha256=eq.${body.expected_sha256}&limit=1`) as DocumentRow[];const document=found[0];if(!document)throw new IntakeError(404,'not_found','This document version was not found. Refresh the checklist.');
  if(!document.storage_path||!document.requested_month||!document.byte_size||!document.mime_type||!document.uploaded_by)throw new IntakeError(409,'legacy_source','This existing source needs a new monthly aggregate upload before automated review can run.');
  if(document.storage_path!==`${document.uploaded_by}/${document.id}/source.${uploadExtension(document.file_name)}`)throw new IntakeError(409,'invalid_storage_path','The reserved source path could not be verified.');
  if(document.status==='quarantined')throw new IntakeError(409,'quarantined','This source is quarantined. Upload an aggregate-only corrected file.');
  if(document.status==='reviewing'&&document.review_started_at&&Date.now()-Date.parse(document.review_started_at)<600000){if(body.mapping!==undefined)throw new IntakeError(409,'mapping_review_in_progress','This source is already being reviewed. Your new mapping has not been saved. Wait for that review to finish, then retry this mapping.');return response(request,{document:safeDocument(document),review_in_progress:true});}
  const stored=await fetcher(`${environment.SUPABASE_URL.replace(/\/$/,'')}/storage/v1/object/authenticated/cheshire-intake/${document.storage_path}`,{headers:{Authorization:`Bearer ${environment.SUPABASE_SERVICE_ROLE_KEY}`,apikey:environment.SUPABASE_SERVICE_ROLE_KEY},signal:AbortSignal.timeout(30000)});
  if(!stored.ok)throw new IntakeError(stored.status===404?409:503,'file_unavailable','The file has not finished uploading or is temporarily unavailable. Retry the same upload to resume; it has not been marked received.');
  const bytes=await readBounded(stored);if(bytes.length!==document.byte_size||await sha256(bytes)!==document.content_sha256)throw new IntakeError(422,'hash_mismatch','The stored source does not match the reserved file size and hash. Upload the original file again under a new verified version.');
  const submittedMapping=body.mapping;
  const priorMapping=document.validation?.mapping;
  const selectedMapping=submittedMapping!==undefined?submittedMapping:(priorMapping?mappingFromProvenance(priorMapping):undefined);
  let confirmedMapping:MappingProvenance|undefined;
  if(selectedMapping!==undefined){try{const checked=validateMapping(selectedMapping,document.content_sha256,document.source_type);confirmedMapping={...checked,confirmed_by:submittedMapping!==undefined?user.id:priorMapping!.confirmed_by,confirmed_at:submittedMapping!==undefined?new Date().toISOString():priorMapping!.confirmed_at};}catch(error){throw new IntakeError(400,'invalid_mapping',error instanceof Error?error.message:'The mapping could not be verified.');}}
  reviewToken=crypto.randomUUID();const claimFilter=`id=eq.${document.id}&content_sha256=eq.${document.content_sha256}&status=eq.${document.status}&review_revision=${typeof document.review_revision==='string'?`eq.${document.review_revision}`:'is.null'}${document.status==='reviewing'?`&review_started_at=eq.${encodeURIComponent(document.review_started_at??'')}`:''}`;
  const claimed=await db(`cheshire_intake_document?${claimFilter}`,{method:'PATCH',body:JSON.stringify({status:'reviewing',review_token:reviewToken,review_started_at:new Date().toISOString(),failure_message:null})}) as DocumentRow[];
  if(!claimed.length)throw new IntakeError(409,'review_race','This source is already being reviewed. Refresh the checklist.');reviewing=document;
  let result:ReviewResult|undefined;let table;
  try{table=confirmedMapping?parseMappedUpload(bytes,document.file_name,document.mime_type,document.source_type,document.content_sha256,mappingFromProvenance(confirmedMapping)).table:parseUpload(bytes,document.file_name,document.mime_type,document.source_type);}catch(error){result=reviewWithoutExtraction(error instanceof Error?error.message:'The source could not be parsed safely.');table=null;}
  const month=document.requested_month.slice(0,7);const context:ValidationContext={};const dependencies:Record<string,string>={};const dependencyRevisions:Record<string,string>={};
  if(table){
   const scopeRows=await db(`cheshire_intake_document?requested_month=eq.${document.requested_month}&source_type=in.(coverage_manifest,payroll)&order=created_at.desc,id.desc&limit=100`) as DocumentRow[];
   if(scopeRows.length>=100)throw new IntakeError(409,'scope_review_limit','Too many source versions need reconciliation before this monthly scope can be verified.');const superseded=new Set(scopeRows.map(row=>row.supersedes_id).filter(Boolean));const active=scopeRows.filter(row=>!superseded.has(row.id));const manifests=active.filter(row=>row.source_type==='coverage_manifest');const payrolls=active.filter(row=>row.source_type==='payroll');const manifest=manifests.length===1?manifests[0]:undefined;const payroll=payrolls.length===1?payrolls[0]:undefined;
   if(!['coverage_manifest','overhead'].includes(document.source_type)&&manifest&&complete(manifest,month)&&typeof manifest.review_revision==='string'&&manifest.validation_scope){context.expectedProvidersBySource=manifest.validation_scope.expectedProvidersBySource as ValidationContext['expectedProvidersBySource'];context.expectedDistricts=manifest.validation_scope.expectedDistricts as string[];context.expectedSchoolProvidersByDistrict=manifest.validation_scope.expectedSchoolProvidersByDistrict as Record<string,string[]>;dependencies.coverage_manifest=`${manifest.id}:${manifest.content_sha256}`;const revision=dependencyRevision(manifest as MetricDocument);if(revision)dependencyRevisions.coverage_manifest=revision;}
   if(document.source_type==='staff_allocation'&&payroll&&complete(payroll,month)&&payroll.validation_scope&&manifest&&payroll.validation_dependencies?.coverage_manifest===`${manifest.id}:${manifest.content_sha256}`&&typeof manifest.review_revision==='string'&&(payroll.validation_dependency_revisions as Record<string,string>|undefined)?.coverage_manifest===manifest.review_revision){context.verifiedPayrollStaffIds=payroll.validation_scope.staffIds as string[];dependencies.payroll=`${payroll.id}:${payroll.content_sha256}`;const revision=dependencyRevision(payroll as MetricDocument);if(revision)dependencyRevisions.payroll=revision;}
   if(document.source_type==='operating_expenses'){const baselines=await db('cheshire_finance_snapshot?id=eq.current-overhead&select=cadence,cost_basis,effective_month,overhead_rows,revision_id');const baseline=baselines[0];if(baseline&&(baseline.cost_basis==='fixed_monthly_baseline'||baseline.effective_month===document.requested_month)){dependencies.overhead_reference=baseline.revision_id;context.overheadByLocationCategory={};for(const row of baseline.overhead_rows??[]){context.overheadByLocationCategory[JSON.stringify([row.location,row.category])]=row.amount===null?null:Math.round(Number(row.amount)*100);}}}
   if(document.source_type==='overhead'){const baselines=await db('cheshire_finance_snapshot?id=eq.current-overhead&select=source_sha256,cadence,cost_basis,basis_note,basis_confirmed_at,revision_id,overhead_rows');result=reviewFixedBaseline(table,document.content_sha256,baselines[0])??undefined;if(result)dependencies.overhead_reference=baselines[0].revision_id;}
   result??=validateTable(table,document.source_type,month,context);
  }else result??=reviewWithoutExtraction('The file was received, but PDF and image scans need manual review or a CSV/XLSX aggregate export. No OCR or AI file transfer has been performed.');
  if(confirmedMapping)result.mapping=confirmedMapping;
  let scope:Record<string,unknown>|null=null;
  if(result.status==='complete'&&table){
   if(document.source_type==='coverage_manifest'){const providers:Partial<Record<SourceType,Record<string,string[]>>>={};const districts=new Set<string>();const schoolProviders:Record<string,string[]>={};for(const row of table.rows){const kind=row.source_type as SourceType;providers[kind]??={};providers[kind]![row.location!]??=[];if(row.coverage_status==='active')providers[kind]![row.location!].push(row.provider_id!);if(kind==='school_billing'&&row.coverage_status==='active'&&row.district&&row.district!=='not_applicable'){districts.add(row.district);schoolProviders[row.district]??=[];schoolProviders[row.district].push(row.provider_id!);}}scope={expectedProvidersBySource:providers,expectedDistricts:[...districts],expectedSchoolProvidersByDistrict:schoolProviders};}
   if(document.source_type==='payroll')scope={staffIds:[...new Set(table.rows.map(row=>row.staff_id))]};
  }
  const limit=aiConfiguration.ai_monthly_limit;
  if(table&&result.status!=='quarantined'&&aiConfiguration.ai_enabled&&Number.isInteger(limit)&&limit>0&&limit<=10&&environment.HF_TOKEN){
   const key=await sha256(new TextEncoder().encode([document.content_sha256,document.source_type,month,result.validator_version,JSON.stringify(Object.entries(dependencies).sort()),JSON.stringify(mappingFromProvenance(confirmedMapping)??null)].join(':')));
   let reserved=false;try{reserved=await db('rpc/reserve_cheshire_intake_ai_call',{method:'POST',body:JSON.stringify({p_cache_key:key,p_limit:limit})});}catch{result.ai_status='unavailable';result.ai_note='AI budget verification was unavailable. Deterministic review was preserved; no AI request was made.';}
   if(reserved===true){try{
    const ai=await fetcher('https://router.huggingface.co/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${environment.HF_TOKEN}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(20000),body:JSON.stringify({model:'openai/gpt-oss-120b:cerebras',messages:[{role:'system',content:'Review canonical document-validation metadata only. Return JSON with exactly check_codes (an array of failed check keys to prioritize) and source_types (an array of relevant source type codes). No prose, no values, no completion decision. Allowed check keys: '+REQUIRED_CHECKS.join(',')+'. Allowed source types: '+SOURCE_TYPES.join(',')+'.'}, {role:'user',content:JSON.stringify(sanitizedAiSummary(result,document.source_type))}],max_tokens:256,temperature:0,reasoning_effort:'low'})});
    if(!ai.ok)throw new Error('AI unavailable');const payload=await ai.json();const content=payload?.choices?.[0]?.message?.content;if(typeof content!=='string'||content.length>4000)throw new Error('Invalid AI response');const suggestion=JSON.parse(content);if(!suggestion||typeof suggestion!=='object'||Array.isArray(suggestion)||Object.keys(suggestion).some(key=>!['check_codes','source_types'].includes(key))||!Array.isArray(suggestion.check_codes)||!Array.isArray(suggestion.source_types)||suggestion.check_codes.length>REQUIRED_CHECKS.length||suggestion.source_types.length>SOURCE_TYPES.length||suggestion.check_codes.some((key:unknown)=>!result!.checks.some(check=>check.key===key&&!check.passed))||suggestion.source_types.some((key:unknown)=>!SOURCE_TYPES.includes(key as never)))throw new Error('Invalid AI response');
    result.ai_suggestions={check_codes:[...new Set(suggestion.check_codes)] as typeof REQUIRED_CHECKS,source_types:[...new Set(suggestion.source_types)] as SourceType[]};result.ai_status='assisted';result.ai_note='AI reviewed sanitized checklist metadata. The deterministic checks remain authoritative.';
   }catch{result.ai_status='unavailable';result.ai_note='AI assistance was unavailable. The deterministic review is preserved; the call will not automatically repeat.';}}
   else{const sameDependencies=JSON.stringify(Object.entries(document.validation_dependencies??{}).sort())===JSON.stringify(Object.entries(dependencies).sort());const prior=document.validation;const sameMapping=JSON.stringify(mappingFromProvenance(prior?.mapping)??null)===JSON.stringify(mappingFromProvenance(confirmedMapping)??null);const reusable=sameDependencies&&sameMapping&&prior?.validator_version===result.validator_version&&prior.ai_status==='assisted'&&prior.ai_suggestions&&prior.ai_suggestions.check_codes.every(key=>result!.checks.some(check=>check.key===key&&!check.passed));if(reusable){result.ai_status='assisted';result.ai_suggestions=prior.ai_suggestions;result.ai_note='The saved sanitized priority hint was reused. No additional AI request was made.';}else{result.ai_status='unavailable';result.ai_note??='AI assistance is unavailable for this review because its call was already reserved or the monthly cap was reached. Deterministic checks remain available.';}}
  }
  const normalizedRows=result.status==='complete'&&table?normalizeMetrics(table,document.source_type,month,result):[];
  const normalizationBlocker=result.status==='complete'&&table?normalizationIssue(table,document.source_type):null;
  const saved=await db('rpc/finalize_cheshire_intake_review',{method:'POST',body:JSON.stringify({p_document_id:document.id,p_content_sha256:document.content_sha256,p_review_token:reviewToken,p_validation:result,p_scope:scope,p_dependencies:dependencies,p_dependency_revisions:dependencyRevisions,p_normalizer_version:NORMALIZER_VERSION,p_rows:normalizedRows,p_normalization_issue:normalizationBlocker})}) as DocumentRow[];
  if(!saved.length)throw new IntakeError(409,'stale_review','A newer review replaced this response. Refresh the checklist.');
  reviewing=null;return response(request,{document:safeDocument(saved[0])});
 }catch(error){
  const safe=error instanceof IntakeError?error:new IntakeError(503,'review_unavailable','The private review could not finish. Your source has not been marked complete. Please retry.');
  if(reviewing&&reviewToken){try{await db(`cheshire_intake_document?id=eq.${reviewing.id}&content_sha256=eq.${reviewing.content_sha256}&review_token=eq.${reviewToken}&status=eq.reviewing`,{method:'PATCH',body:JSON.stringify({status:'error',failure_message:safe.message})});}catch{/* Do not log source data. A stale in-progress review can be retried after ten minutes. */}}
  return response(request,{error:safe.message,code:safe.code},safe.status);
 }
}

