import type {MappingProvenance} from './cheshire-report-mapping.ts';
/** Shared, deterministic document requirements. No customer files or amounts belong here. */
export const MAX_PAYER_LENGTH = 160;
export const INTAKE_LOCATIONS = ['Cheshire', 'Cromwell', 'Guilford', 'Meriden', 'Orange', 'Pool', 'Torrington'] as const;
export const INTAKE_EXPENSE_CATEGORIES = ['Rent', 'Utilities phone', 'utilities electric', 'utilities gas', 'insurance', 'cleaning service', 'Repair/maintenance', 'plow/mow', 'dumpster', 'elevator contract', 'alarm', 'Supplies', 'EMR', 'Education', 'auto', 'ccmc consultant', 'fees (ADP/collections)', 'microsoft license', 'student loan repayment', 'virtual assistant'] as const;
export const SOURCE_TYPES = ['coverage_manifest','insurance_revenue','clinic_activity','school_billing','cash_programs','payroll','staff_allocation','operating_expenses','overhead'] as const;
export type SourceType = typeof SOURCE_TYPES[number];
export type Requirement = {id: SourceType; title: string; shortTitle: string; description: string; fields: string[]; optionalFields?:string[]; locationCoverage: 'all-seven' | 'reported'; note: string};
export const INTAKE_REQUIREMENTS: Requirement[] = [
 {id:'coverage_manifest',title:'Monthly reporting coverage',shortTitle:'Monthly coverage',description:'The approved list of expected source types, providers, locations and school districts for this month.',fields:['reporting_month','source_type','location','provider_id','district','coverage_status'],locationCoverage:'all-seven',note:'Use an explicit not_applicable for district when a row is not a school contract. This manifest determines required scope. For operating expenses, provider_id is the expected expense category/scope ID at each allocated location.'},
 {id:'insurance_revenue',title:'Insurance payments & provider summary',shortTitle:'Insurance payments',description:'The full monthly PracticePro payment export and provider totals, with no patient-level details.',fields:['reporting_month','date_basis','currency','location','therapist_id','payer','units','charges','insurance_payments','patient_payments','write_offs','adjustments','outstanding_balance','report_total'],locationCoverage:'all-seven',note:'Payer is the aggregate insurance organization identifier or name, never a patient/member ID. Payment-date revenue must stay separate from service-date activity. Insurance copays are not cash specialty-program revenue.'},
 {id:'clinic_activity',title:'Appointments & therapist activity',shortTitle:'Clinic activity',description:'Monthly aggregate visits and units by office and therapist, including cancellations and no-shows.',fields:['reporting_month','date_basis','location','therapist_id','scheduled_visits','completed_visits','cancellations','no_shows','units','worked_hours','report_total'],locationCoverage:'all-seven',note:'The control total is completed visits. No patient names, IDs, diagnoses or clinical notes.'},
 {id:'school_billing',title:'School billing & applicable contract rates',shortTitle:'School billing',description:'District billing, hours, current contract rates and invoice totals for the month.',fields:['reporting_month','currency','district','therapist_id','billing_basis','billed_quantity','contract_rate','rate_effective_start','rate_effective_end','invoice_total','report_total'],locationCoverage:'reported',note:'Billed hours or visits × the applicable contract rate must reconcile to invoice totals. Missing or differently structured rate terms require review.'},
 {id:'cash_programs',title:'Cash specialty-program income',shortTitle:'Cash programs',description:'Monthly program income by office, with a source total and explicit zero-activity locations.',fields:['reporting_month','location','program','income','report_total'],optionalFields:['currency'],locationCoverage:'all-seven',note:'Include a currency column with USD before monetary metrics can be displayed. Include specialty programs only. Do not duplicate patient payments from the insurance export.'},
 {id:'payroll',title:'Payroll & fully loaded employment costs',shortTitle:'Payroll costs',description:'Monthly staff costs including wages, employer taxes, benefits, PTO and bonuses.',fields:['reporting_month','staff_id','role','payroll_cost_basis','cash_pay','payroll_taxes','benefits','paid_hours','report_total'],optionalFields:['pto_cost','bonuses','currency'],locationCoverage:'reported',note:'Include a currency column with USD before monetary metrics can be displayed. Declare gross_cash_inclusive (cash pay already includes PTO/bonuses) or disjoint_components. Inclusive pay is never added to its PTO/bonus breakdown again.'},
 {id:'staff_allocation',title:'Staff time & allocation',shortTitle:'Staff allocation',description:'Staff allocation percentages by location and insurance, school or cash work for the month.',fields:['reporting_month','staff_id','location','revenue_stream','allocation_percent'],locationCoverage:'reported',note:'Each staff member must total 100%. A matching verified payroll roster is required; no automatic 50/50 split.'},
 {id:'operating_expenses',title:'Operating & shared expenses',shortTitle:'Operating & shared costs',description:'QuickBooks or equivalent non-payroll expenses, including central legal, tax, marketing, technology and administration costs.',fields:['reporting_month','expense_id','expense_category','cost_scope','location','source_amount','allocated_amount','allocation_percent','overhead_overlap','report_total'],optionalFields:['currency'],locationCoverage:'reported',note:'Include a currency column with USD before monetary metrics can be displayed. Shared allocations must conserve the original expense. Reconcile EMR, ADP, insurance and other amounts already included in the fixed location baseline so they are not counted twice.'},
 {id:'overhead',title:'Location overhead & operating expenses',shortTitle:'Location overhead',description:'All seven locations and each expense category, including explicit zeros and a source control total.',fields:['reporting_month','location','expense_category','amount','report_total'],optionalFields:['currency'],locationCoverage:'all-seven',note:'Include a currency column with USD before monetary metrics can be displayed. Blank amounts are unknown. Resolve duplicate EMR, payroll/collection and centrally allocated costs before profit calculation.'},
];
export type IntakeStatus = 'uploading'|'received'|'reviewing'|'incomplete'|'complete'|'error'|'quarantined';
export type CheckKey = 'document_type'|'reporting_period'|'required_fields'|'row_values'|'location_coverage'|'reconciliation'|'privacy';
export const REQUIRED_CHECKS: CheckKey[] = ['document_type','reporting_period','required_fields','row_values','location_coverage','reconciliation','privacy'];
export type ReviewCheck = {key: CheckKey; passed: boolean; message: string};
export type ReviewResult = {cumulative_report?:unknown;mapping?:MappingProvenance;validator_version:'cheshire-intake-v1'|'source-audit-v1';status:'incomplete'|'complete'|'quarantined';reported_month:string|null;checks:ReviewCheck[];missing_items:string[];row_count?:number;reported_metrics?:{label:string;value:number;unit:'count'|'USD'|'hours'|'units';note?:string}[];covered_locations:string[];canonical_fields:string[];ai_status:'not_requested'|'pending'|'assisted'|'unavailable';ai_note?:string;ai_suggestions?:{check_codes:CheckKey[];source_types:SourceType[]};related_requests?:{target_source_type:SourceType;title:string;period_label:string;scope_label:string;unlocks:string;missing_items:string[]}[];reference_basis?:'fixed_monthly_baseline';missing_amounts?:{location:string;category:string;source_cell?:string}[]};
export type IntakeDocument = {id:string;source_type:SourceType;requested_month:string|null;reported_month:string|null;file_name:string;content_sha256:string;status:IntakeStatus;created_at:string;reviewed_at:string|null;review_revision?:string|null;validation_dependency_revisions?:Record<string,string>;source_origin:'portal_upload'|'existing_source';storage_path:string|null;validation:ReviewResult|null;failure_message:string|null;supersedes_id?:string|null;validation_dependencies?:Record<string,string>;validation_scope?:Record<string,unknown>;source_period_label?:string|null;source_scope_label?:string|null;figure_unlocked?:string|null};
export type ParsedTable = {headers:string[];rows:Record<string,string|null>[];sourceRows:number[];sourcePeriod:string|null;controlTotal:string|null;warnings:string[];blockedFields:string[]};
export type ValidationContext = {verifiedPayrollStaffIds?:string[];expectedDistricts?:string[];expectedSchoolProvidersByDistrict?:Record<string,string[]>;overheadByLocationCategory?:Record<string,number|null>;expectedProvidersBySource?:Partial<Record<SourceType,Record<string,string[]>>>};
const MONTH=/^\d{4}-(0[1-9]|1[0-2])$/;
export function isMonth(value:unknown): value is string {return typeof value==='string'&&MONTH.test(value)&&!value.startsWith('0000-');}
export function canonicalField(value:string){return value.toLowerCase().replace(/[^a-z0-9]/g,'');}
const ALIASES:Record<string,string[]>={
 payer:['payer','payerid','payername','payor','payorid','payorname','insurancecompany','insurancepayer'],
 expense_id:['expenseid','transactionid'],cost_scope:['costscope'],source_amount:['sourceamount','originalamount'],allocated_amount:['allocatedamount'],overhead_overlap:['overheadoverlap','overlapstatus'],coverage_status:['coveragestatus','scopestatus'],source_type:['sourcetype','documenttype'],provider_id:['providerid','provider','therapist','staffid'],date_basis:['datebasis','datefieldmeaning'],currency:['currency','currencycode'],charges:['charges','chargeamount'],write_offs:['writeoffs','totalwriteoffs'],outstanding_balance:['outstandingbalance','balance'],billing_basis:['billingbasis'],billed_quantity:['billedquantity','billedhours','billedvisits'],rate_effective_start:['rateeffectivestart','ratefrom'],rate_effective_end:['rateeffectiveend','ratethrough'],
 reporting_month:['reportingmonth','accountingmonth','month','period'],location:['location','office','clinic','facility'],therapist_id:['therapistid','therapist','provider','providerid','treatingprovider'],staff_id:['staffid','employeeid','employee','staff','therapistid','therapist','provider'],
 insurance_payments:['insurancepayments','insurancepayment','insuranceincome','insurance'],patient_payments:['patientpayments','patientpayment','copays','patientincome'],adjustments:['adjustments','otheradjustments'],report_total:['reporttotal','controltotal','sourcetotal','grandtotal'],
 scheduled_visits:['scheduledvisits','appointmentsscheduled','scheduled','patientsscheduled'],completed_visits:['completedvisits','visitscompleted','visits','arrived','patientsarrived'],cancellations:['cancellations','canceled','cancelled'],no_shows:['noshows','noshow'],units:['units','unitsbilled','totalunitsbilled'],worked_hours:['workedhours','hoursworked'],district:['district','schooldistrict','school'],billed_hours:['billedhours','billablehours','hours'],contract_rate:['contractrate','hourlyrate','rate'],invoice_total:['invoicetotal','invoiceamount'],program:['program','programname','specialtyprogram'],income:['income','revenue','programincome'],role:['role','category','staffrole'],payroll_cost_basis:['payrollcostbasis','costbasis'],cash_pay:['cashpay','grosscashpay','basecashpay','grosspay','wages','salary'],payroll_taxes:['payrolltaxes','employertaxes'],benefits:['benefits','benefitcost'],pto_cost:['ptocost','paidtimeoffcost'],bonuses:['bonuses','bonus'],paid_hours:['paidhours'],revenue_stream:['revenuestream','stream','servicetype'],allocation_percent:['allocationpercent','allocationpercentage','allocationpct','percent'],expense_category:['expensecategory','category','expense'],amount:['amount','cost','monthlyamount'],
};
const BLOCKED_HEADERS=new Set(['patientname','patientid','patient','patientdob','dateofbirth','dob','mrn','medicalrecordnumber','diagnosis','diagnoses','clinicalnotes','ssn','socialsecuritynumber','memberid','subscriberid','student','studentname','studentid','childname']);
export function mapHeaders(headers:string[],sourceType:SourceType){
 const requirement=INTAKE_REQUIREMENTS.find(item=>item.id===sourceType)!;
 const mapped=headers.map(header=>[...requirement.fields,...(requirement.optionalFields??[])].find(field=>(ALIASES[field]??[canonicalField(field)]).includes(canonicalField(header)))??'');
 const duplicates=mapped.filter((field,index)=>field&&mapped.indexOf(field)!==index);
 const blocked=headers.filter(header=>{const normalized=canonicalField(header);return BLOCKED_HEADERS.has(normalized)||/(patient|student|child).*(name|identifier|id|birth|dob|address|email|phone|record)/.test(normalized);});
 return {mapped,duplicates:[...new Set(duplicates)],blocked,unmapped:headers.map((_,index)=>index).filter(index=>!mapped[index])};
}
/** CSV parser handles quoted separators/newlines and rejects ragged or over-limit input. */
export function parseDelimitedMatrix(text:string,preserveEmptyRows=false):(string|null)[][] {
 if(text.length>5_000_000)throw new Error('The text export exceeds the review limit.');
 const cleaned=text.replace(/^\uFEFF/,'');const firstLine=cleaned.split(/\r?\n/,1)[0];const delimiter=firstLine.includes('\t')&&!firstLine.includes(',')?'\t':',';
 const matrix:string[][]=[];let row:string[]=[];let field='';let quoted=false;let closedQuote=false;
 for(let index=0;index<cleaned.length;index++){
  const char=cleaned[index];
  if(quoted){if(char==='"'){if(cleaned[index+1]==='"'){field+='"';index++;}else{quoted=false;closedQuote=true;}}else field+=char;}
  else if(char==='"'){if(field.length||closedQuote)throw new Error('Invalid quoting in the delimited export.');quoted=true;}
  else if(char===delimiter){row.push(field.trim());field='';closedQuote=false;}
  else if(char==='\n'||char==='\r'){if(char==='\r'&&cleaned[index+1]==='\n')index++;row.push(field.trim());if(preserveEmptyRows||row.some(value=>value!==''))matrix.push(row);row=[];field='';closedQuote=false;}
  else {if(closedQuote&&!/\s/.test(char))throw new Error('Unexpected text after a quoted field.');field+=char;}
  if(matrix.length>10000||row.length>100||field.length>20000)throw new Error('The export exceeds the row, column or cell review limit.');
 }
 if(quoted)throw new Error('An export field has an unclosed quote.');row.push(field.trim());if(row.some(value=>value!==''))matrix.push(row);
 return matrix;
}
export function parseDelimited(text:string,sourceType:SourceType):ParsedTable {return tableFromMatrix(parseDelimitedMatrix(text),sourceType);}
export function tableFromMatrix(matrix:(string|null)[][],sourceType:SourceType):ParsedTable {
 if(!matrix.length||matrix.length>10001)throw new Error('Provide a non-empty export with at most 10,000 rows.');
 const headers=matrix[0].map(value=>(value??'').trim());if(headers.length>100||!headers.some(Boolean))throw new Error('The export needs a header row.');
 const mapping=mapHeaders(headers,sourceType);const warnings=mapping.duplicates.map(field=>`More than one column maps to ${field}.`);const unmapped=mapping.unmapped.filter(index=>matrix.slice(1).some(row=>row[index]!==null&&row[index]!==undefined&&String(row[index]).trim()!==''));if(unmapped.length)warnings.push(`Unmapped nonempty columns require manual review: ${unmapped.map(index=>index+1).join(', ')}. Remove patient-level detail and use the required column definitions.`);if(matrix.slice(1).some(row=>row.some(value=>typeof value==='string'&&/^[=@]|^\+[A-Za-z(]/.test(value))))warnings.push('Formula-like text requires review; formulas are never executed.');
 const rows:Record<string,string|null>[]=[];const sourceRows:number[]=[];
 matrix.slice(1).forEach((values,index)=>{
  if(!values.some(value=>value!==null&&String(value).trim()!==''))return;
  if(values.length!==headers.length)throw new Error(`Row ${index+2} has a different number of columns from the header.`);
  const record:Record<string,string|null>={};mapping.mapped.forEach((field,col)=>{if(field)record[field]=values[col]===null||String(values[col]).trim()===''?null:String(values[col]).trim();});rows.push(record);sourceRows.push(index+2);
 });
 const periods=[...new Set(rows.map(row=>row.reporting_month).filter((value):value is string=>Boolean(value)))];
 const controls=[...new Set(rows.map(row=>row.report_total).filter((value):value is string=>Boolean(value)))];
 return {headers:mapping.mapped.filter(Boolean),rows,sourceRows,sourcePeriod:periods.length===1&&isMonth(periods[0])?periods[0]:null,controlTotal:controls.length===1?controls[0]:null,warnings,blockedFields:mapping.blocked};
}
function decimal(value:string|null|undefined,{signed=false,precision=2,money=false}={}){
 if(value==null)return null;let normalized=value;
 if(money){if(signed&&/^\(.*\)$/.test(normalized))normalized='-'+normalized.slice(1,-1);normalized=normalized.replace(/^(-?)\$/, '$1');if(!/^-?(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/.test(normalized))return null;normalized=normalized.replaceAll(',','');}
 if(!(signed?/^-?\d+(?:\.\d+)?$/:/^\d+(?:\.\d+)?$/).test(normalized))return null;
 const fraction=normalized.split('.')[1]??'';if(fraction.length>precision)return null;
 const number=Number(normalized);return Number.isFinite(number)&&Math.abs(number)<=1_000_000_000?number:null;
}
function cents(value:string|null|undefined,signed=false){const number=decimal(value,{signed,money:true});return number===null?null:Math.round(number*100);}
function validDate(value:string|null|undefined){if(!value||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(value+'T00:00:00Z');return Number.isFinite(date.valueOf())&&date.toISOString().slice(0,10)===value;}
function humanField(field:string){return field.replaceAll('_',' ');}
export function validateTable(table:ParsedTable,sourceType:SourceType,requestedMonth:string,context:ValidationContext={}):ReviewResult {
 if(!isMonth(requestedMonth))throw new Error('Choose a valid reporting month.');
 const requirement=INTAKE_REQUIREMENTS.find(item=>item.id===sourceType);if(!requirement)throw new Error('Unsupported source type.');
 const missing:string[]=[];const checks:ReviewCheck[]=[];const add=(key:CheckKey,passed:boolean,message:string)=>{checks.push({key,passed,message});if(!passed)missing.push(message);};
 const privacyOk=table.blockedFields.length===0&&!table.rows.some(row=>Object.values(row).some(value=>value&&/\b\d{3}-\d{2}-\d{4}\b/.test(value)));
 add('privacy',privacyOk,privacyOk?'No blocked identifier columns detected.':'Restricted personal or patient-data markers were detected. Remove identifiers before review. Nothing will be sent to AI.');
 add('document_type',table.rows.length>0&&table.warnings.length===0,table.warnings.length?table.warnings.join(' '):table.rows.length?'Readable tabular export.':'The file contains no usable detail rows.');
 const periods=[...new Set(table.rows.map(row=>row.reporting_month))];const periodOk=periods.length===1&&periods[0]===requestedMonth&&table.sourcePeriod===requestedMonth;
 add('reporting_period',periodOk,periodOk?`Source period matches ${requestedMonth}.`:`The source must explicitly identify ${requestedMonth} on every detail row; the selected upload month alone is not period evidence.`);
 const absent=requirement.fields.filter(field=>!table.headers.includes(field));
 add('required_fields',absent.length===0,absent.length?`Missing required fields: ${absent.map(humanField).join(', ')}.`:'All required columns are present.');
 const moneyFields=sourceType==='insurance_revenue'?['charges','insurance_payments','patient_payments','write_offs','adjustments','outstanding_balance']:sourceType==='school_billing'?['contract_rate','invoice_total']:sourceType==='cash_programs'?['income']:sourceType==='payroll'?['cash_pay','payroll_taxes','benefits']:sourceType==='overhead'?['amount']:sourceType==='operating_expenses'?['source_amount','allocated_amount']:[];
 const countFields=sourceType==='insurance_revenue'?['units']:sourceType==='clinic_activity'?['scheduled_visits','completed_visits','cancellations','no_shows','units']:[];
 const decimalFields=sourceType==='clinic_activity'?['worked_hours']:sourceType==='school_billing'?['billed_quantity']:sourceType==='payroll'?['paid_hours']:['staff_allocation','operating_expenses'].includes(sourceType)?['allocation_percent']:[];
 const valueIssues:string[]=[];const keySet=new Set<string>();const missingAmounts:NonNullable<ReviewResult['missing_amounts']>=[];
 table.rows.forEach((row,index)=>{
  const label=sourceType==='overhead'&&INTAKE_LOCATIONS.includes(row.location as typeof INTAKE_LOCATIONS[number])&&INTAKE_EXPENSE_CATEGORIES.includes(row.expense_category as typeof INTAKE_EXPENSE_CATEGORIES[number])?`${row.location} / ${row.expense_category}`:`Row ${table.sourceRows[index]??index+2}`;
  const blanks=requirement.fields.filter(field=>!['reporting_month','report_total'].includes(field)&&(row[field]===null||row[field]===undefined||row[field]===''));
  if(sourceType==='overhead'&&blanks.includes('amount')&&INTAKE_LOCATIONS.includes(row.location as typeof INTAKE_LOCATIONS[number])&&INTAKE_EXPENSE_CATEGORIES.includes(row.expense_category as typeof INTAKE_EXPENSE_CATEGORIES[number])&&!missingAmounts.some(cell=>cell.location===row.location&&cell.category===row.expense_category))missingAmounts.push({location:row.location!,category:row.expense_category!});
  if(blanks.length)valueIssues.push(`${label}: missing ${blanks.map(humanField).join(', ')}.`);
  for(const field of moneyFields)if(!blanks.includes(field)&&cents(row[field],field==='adjustments')===null)valueIssues.push(`${label}: invalid ${humanField(field)}.`);
  for(const field of countFields){if(blanks.includes(field))continue;const value=decimal(row[field],{precision:0});if(value===null)valueIssues.push(`${label}: ${humanField(field)} must be a non-negative whole number.`);}
  for(const field of decimalFields)if(!blanks.includes(field)&&decimal(row[field],{precision:4})===null)valueIssues.push(`${label}: invalid ${humanField(field)}.`);
  if(sourceType==='coverage_manifest'){if(row.source_type&&(row.source_type==='coverage_manifest'||!SOURCE_TYPES.includes(row.source_type as SourceType)))valueIssues.push(`${label}: unknown expected source type.`);if(!['active','not_applicable'].includes(row.coverage_status??''))valueIssues.push(`${label}: scope must explicitly be active or not_applicable.`);if(row.coverage_status==='not_applicable'&&(row.provider_id!=='not_applicable'||row.district!=='not_applicable'))valueIssues.push(`${label}: not-applicable scope must not claim provider or district activity.`);if(row.coverage_status==='active'&&row.source_type!=='overhead'&&row.provider_id==='not_applicable')valueIssues.push(`${label}: active scope needs a provider or program ID.`);if(row.coverage_status==='active'&&row.source_type==='school_billing'&&row.district==='not_applicable')valueIssues.push(`${label}: active school scope needs a district.`);}
  if(['insurance_revenue','school_billing'].includes(sourceType)&&row.currency!=='USD')valueIssues.push(`${label}: currency must be explicitly identified as USD for this reporting workspace.`);
  if(sourceType==='insurance_revenue'&&row.payer&&row.payer.length>MAX_PAYER_LENGTH)valueIssues.push(`${label}: payer identifier/name must be no longer than ${MAX_PAYER_LENGTH} characters.`);
  if(['cash_programs','payroll','operating_expenses','overhead'].includes(sourceType)&&row.currency!==undefined&&row.currency!=='USD')valueIssues.push(`${label}: supplied currency must be explicitly USD.`);
  if(sourceType==='insurance_revenue'&&!['payment_date','service_date','report_as_of'].includes(row.date_basis??''))valueIssues.push(`${label}: identify payment_date, service_date or report_as_of; date meanings are not inferred.`);
  if(sourceType==='clinic_activity'&&row.date_basis!=='service_date')valueIssues.push(`${label}: monthly activity needs service-date attribution. Week-ending or mixed-period totals require an approved allocation or a finer-grained export.`);
  if(sourceType==='school_billing'&&!['hours','visits'].includes(row.billing_basis??''))valueIssues.push(`${label}: billing basis must identify hours or visits.`);
  if(sourceType==='payroll'){if(!['gross_cash_inclusive','disjoint_components'].includes(row.payroll_cost_basis??''))valueIssues.push(`${label}: declare whether cash pay already includes PTO and bonuses.`);if(row.payroll_cost_basis==='disjoint_components'&&['pto_cost','bonuses'].some(field=>cents(row[field])===null))valueIssues.push(`${label}: disjoint payroll components require explicit PTO and bonus amounts.`);}
  const keyFields=sourceType==='insurance_revenue'?['location','therapist_id','payer','date_basis']:sourceType==='coverage_manifest'?['source_type','location','provider_id','district']:sourceType==='overhead'?['location','expense_category']:sourceType==='payroll'?['staff_id']:sourceType==='operating_expenses'?['expense_id','location']:sourceType==='staff_allocation'?['staff_id','location','revenue_stream']:null;
  if(keyFields){const key=JSON.stringify(keyFields.map(field=>row[field]));if(keySet.has(key))valueIssues.push(`${label}: duplicate reporting key.`);keySet.add(key);}
  if(sourceType==='overhead'&&row.expense_category&&!INTAKE_EXPENSE_CATEGORIES.includes(row.expense_category as typeof INTAKE_EXPENSE_CATEGORIES[number]))valueIssues.push(`${label}: expense category is not in the agreed workbook classification.`);
  if(sourceType==='operating_expenses'){if(!['direct_location','shared_central'].includes(row.cost_scope??''))valueIssues.push(`${label}: identify direct_location or shared_central cost scope.`);if(!['separate','included_in_baseline','needs_review'].includes(row.overhead_overlap??''))valueIssues.push(`${label}: identify whether this cost overlaps the location baseline.`);if(row.overhead_overlap==='needs_review')valueIssues.push(`${label}: expense overlap remains unresolved.`);}
  if(sourceType==='staff_allocation'&&row.revenue_stream&&!['insurance','school_contract','cash_program'].includes(row.revenue_stream))valueIssues.push(`${label}: revenue stream must be insurance, school_contract or cash_program.`);
  if(sourceType==='clinic_activity'){const counts=['scheduled_visits','completed_visits','cancellations','no_shows'].map(field=>decimal(row[field],{precision:0}));if(counts.every(value=>value!==null)&&counts[1]!+counts[2]!+counts[3]!>counts[0]!)valueIssues.push(`${label}: completed visits, cancellations and no-shows exceed scheduled visits.`);}
 });
 add('row_values',valueIssues.length===0,valueIssues.length?`${missingAmounts.length?`${missingAmounts.length} overhead amounts are blank and remain unknown. `:''}${valueIssues.slice(0,8).join(' ')}${valueIssues.length>8?` Plus ${valueIssues.length-8} more issues.`:''}`:'Required detail values are present and structurally valid.');
 const locations=[...new Set(table.rows.map(row=>row.location).filter((value):value is string=>Boolean(value)))];
 const unknownLocations=locations.filter(location=>!INTAKE_LOCATIONS.includes(location as typeof INTAKE_LOCATIONS[number]));
 const missingLocations=requirement.locationCoverage==='all-seven'?INTAKE_LOCATIONS.filter(location=>!locations.includes(location)):[];
 const coverageIssues:string[]=[];
 if(['insurance_revenue','clinic_activity','cash_programs'].includes(sourceType)){
  const expected=context.expectedProvidersBySource?.[sourceType];
  if(!expected||INTAKE_LOCATIONS.some(location=>!Object.hasOwn(expected,location)))coverageIssues.push('A verified same-month provider/location coverage manifest must explicitly address every location for this source.');
  else for(const [location,providers] of Object.entries(expected)){const actual=new Set(table.rows.filter(row=>row.location===location).map(row=>sourceType==='cash_programs'?row.program:row.therapist_id));if(providers.some(provider=>!actual.has(provider)))coverageIssues.push(`${location}: expected provider coverage is incomplete.`);if([...actual].some(provider=>provider&&!providers.includes(provider)))coverageIssues.push(`${location}: one or more provider IDs need scope confirmation.`);}
 }
 if(sourceType==='operating_expenses'){
  const expected=context.expectedProvidersBySource?.operating_expenses;
  if(!expected||INTAKE_LOCATIONS.some(location=>!Object.hasOwn(expected,location)))coverageIssues.push('A verified same-month operating expense category/location scope is required; a reconciled subset is not the complete monthly expense source.');
  else for(const [location,categories] of Object.entries(expected)){const approved=new Set(categories.map(canonicalField));const actual=new Set(table.rows.filter(row=>row.location===location).map(row=>canonicalField(row.expense_category??'')));if([...approved].some(category=>!actual.has(category)))coverageIssues.push(`${location}: expected operating expense categories are missing.`);if([...actual].some(category=>!approved.has(category)))coverageIssues.push(`${location}: operating expense categories need scope confirmation.`);}
 }
 if(unknownLocations.length)coverageIssues.push('Some location names do not match the seven-location reporting scope.');
 if(missingLocations.length)coverageIssues.push(`Additional location sources are needed: ${missingLocations.join(', ')}. This document’s partial coverage is retained; cross-file monthly reconciliation remains required.`);
 if(sourceType==='overhead')for(const location of INTAKE_LOCATIONS){const categories=new Set(table.rows.filter(row=>row.location===location).map(row=>row.expense_category));const count=INTAKE_EXPENSE_CATEGORIES.filter(category=>!categories.has(category)).length;if(count)coverageIssues.push(`${location}: ${count} expense categories are missing.`);}
 if(sourceType==='payroll'){const expected=context.expectedProvidersBySource?.payroll;const ids=expected?[...new Set(Object.values(expected).flat())]:[];if(!expected||INTAKE_LOCATIONS.some(location=>!Object.hasOwn(expected,location))||!ids.length)coverageIssues.push('A verified same-month expected payroll roster is required.');else{const present=new Set(table.rows.map(row=>row.staff_id));if(ids.some(id=>!present.has(id))||[...present].some(id=>id&&!ids.includes(id)))coverageIssues.push('Payroll staff IDs do not match the approved monthly coverage manifest.');}}
 if(sourceType==='school_billing'){
  const expected=context.expectedDistricts??[];if(!expected.length)coverageIssues.push('Confirm the expected school/district roster before company-wide coverage can be verified.');
  else{const present=new Set(table.rows.map(row=>row.district));if(expected.some(district=>!present.has(district))||[...present].some(district=>district&&!expected.includes(district)))coverageIssues.push('One or more expected districts are missing from this monthly export.');const byDistrict=context.expectedSchoolProvidersByDistrict;if(!byDistrict||expected.some(district=>!byDistrict[district]?.length))coverageIssues.push('Verified district/provider contract scope is required.');else for(const district of expected){const providers=new Set(table.rows.filter(row=>row.district===district).map(row=>row.therapist_id));if(byDistrict[district].some(provider=>!providers.has(provider))||[...providers].some(provider=>provider&&!byDistrict[district].includes(provider)))coverageIssues.push('Expected school provider/district coverage is incomplete or unmatched.');}}
 }
 add('location_coverage',coverageIssues.length===0,coverageIssues.length?coverageIssues.join(' '):'Required reporting coverage is present.');
 const reconcileIssues:string[]=[];
 if(sourceType==='coverage_manifest'){
  for(const kind of SOURCE_TYPES.filter(kind=>kind!=='coverage_manifest'))for(const location of INTAKE_LOCATIONS){const scoped=table.rows.filter(row=>row.source_type===kind&&row.location===location);if(!scoped.length)reconcileIssues.push(`${kind}: explicitly declare active or not-applicable scope for ${location}.`);else if(scoped.some(row=>row.coverage_status==='not_applicable')&&scoped.length>1)reconcileIssues.push(`${kind}/${location}: not-applicable and active scope cannot be mixed.`);}
 } else if(sourceType==='operating_expenses'){
  const groups=new Map<string,Record<string,string|null>[]>();for(const row of table.rows){if(row.expense_id){const list=groups.get(row.expense_id)??[];list.push(row);groups.set(row.expense_id,list);}}let total=0;
  for(const rows of groups.values()){const originals=rows.map(row=>cents(row.source_amount));const allocations=rows.map(row=>cents(row.allocated_amount));const percentages=rows.map(row=>decimal(row.allocation_percent,{precision:4}));if(originals.some(value=>value===null)||new Set(originals).size!==1||allocations.some(value=>value===null)||percentages.some(value=>value===null)||Math.abs(percentages.reduce<number>((sum,value)=>sum+(value??0),0)-100)>0.00001||allocations.reduce<number>((sum,value)=>sum+(value??0),0)!==originals[0])reconcileIssues.push('Each shared/direct expense must retain one original amount and allocate exactly 100% of that amount without duplication.');else total+=originals[0]!;for(const row of rows){const original=cents(row.source_amount),allocated=cents(row.allocated_amount),percent=decimal(row.allocation_percent,{precision:4});if(original!==null&&allocated!==null&&percent!==null&&Math.abs(Math.round(original*percent/100)-allocated)>1)reconcileIssues.push('An allocated expense amount does not match its stated percentage.');if(row.cost_scope==='direct_location'&&(rows.length!==1||percent!==100))reconcileIssues.push('A direct location expense must be assigned once at 100%.');const canonicalCategory=INTAKE_EXPENSE_CATEGORIES.find(category=>canonicalField(category)===canonicalField(row.expense_category??''));const knownCategory=Boolean(canonicalCategory);if(knownCategory&&row.overhead_overlap==='separate')reconcileIssues.push('An expense category overlaps the fixed overhead matrix; reconcile the source before treating it as an additional cost.');if(row.overhead_overlap==='included_in_baseline'){const baseline=context.overheadByLocationCategory?.[JSON.stringify([row.location,canonicalCategory??row.expense_category])];if(baseline===null||baseline===undefined||allocated!==baseline)reconcileIssues.push('An included-in-baseline expense does not match a known source-supported location/category amount.');}}}
  const control=cents(table.controlTotal);if(control===null||!Number.isSafeInteger(total)||total!==control)reconcileIssues.push('Unique original expenses do not reconcile to the source report total.');
 } else if(sourceType==='staff_allocation'){
  const totals=new Map<string,number>();for(const row of table.rows){const value=decimal(row.allocation_percent,{precision:4});if(row.staff_id&&value!==null)totals.set(row.staff_id,(totals.get(row.staff_id)??0)+value);}
  if([...totals.values()].some(value=>Math.abs(value-100)>0.00001))reconcileIssues.push('Every staff member’s allocations must sum to 100%.');
  const staff=context.verifiedPayrollStaffIds??[];if(!staff.length)reconcileIssues.push('A verified same-month payroll roster is required to reconcile staff allocation.');
  else if(staff.some(id=>!totals.has(id))||[...totals.keys()].some(id=>!staff.includes(id)))reconcileIssues.push('Allocation staff IDs do not match the verified same-month payroll roster.');
 } else {
  let sum=0;let valid=true;
  for(const row of table.rows){
   const fields=sourceType==='insurance_revenue'?['insurance_payments','patient_payments']:sourceType==='school_billing'?['invoice_total']:sourceType==='cash_programs'?['income']:sourceType==='payroll'?(row.payroll_cost_basis==='disjoint_components'?['cash_pay','payroll_taxes','benefits','pto_cost','bonuses']:['cash_pay','payroll_taxes','benefits']):sourceType==='overhead'?['amount']:['completed_visits'];
   for(const field of fields){const value=sourceType==='clinic_activity'?decimal(row[field],{precision:0}):cents(row[field]);if(value===null)valid=false;else sum+=value;}
   if(sourceType==='school_billing'){const quantity=decimal(row.billed_quantity,{precision:4}),rate=cents(row.contract_rate),invoice=cents(row.invoice_total);if(quantity!==null&&rate!==null&&invoice!==null&&Math.abs(Math.round(quantity*rate)-invoice)>1)reconcileIssues.push('School billed quantity × rate does not reconcile to one or more invoice totals.');const monthStart=requestedMonth+'-01';const end=new Date(Date.UTC(Number(requestedMonth.slice(0,4)),Number(requestedMonth.slice(5,7)),0)).toISOString().slice(0,10);if(!validDate(row.rate_effective_start)||!validDate(row.rate_effective_end)||row.rate_effective_start!>monthStart||row.rate_effective_end!<end)reconcileIssues.push('A source-supported rate period covering the reported month is required; split partial-period contracts into a finer-grained review.');}
   if(sourceType==='insurance_revenue'){const values=['charges','insurance_payments','patient_payments','write_offs','adjustments','outstanding_balance'].map(field=>cents(row[field],field==='adjustments'));if(values.every(value=>value!==null)&&values[0]!==values.slice(1).reduce((sum,value)=>sum+value!,0))reconcileIssues.push('Charges do not reconcile to payments, write-offs, adjustments and outstanding balance. No adjustment has been invented.');}
  }
  const total=sourceType==='clinic_activity'?decimal(table.controlTotal,{precision:0}):cents(table.controlTotal);
  if(total===null)reconcileIssues.push('A single consistent source report/control total is required.');
  else if(!valid||!Number.isSafeInteger(sum)||Math.abs(sum-total)>(sourceType==='clinic_activity'?0:1))reconcileIssues.push('Detail rows do not reconcile to the source report/control total.');
 }
 add('reconciliation',reconcileIssues.length===0,reconcileIssues.length?[...new Set(reconcileIssues)].join(' '):'Source totals and required allocations reconcile.');
 const status=!privacyOk?'quarantined':checks.every(check=>check.passed)?'complete':'incomplete';
 return {validator_version:'cheshire-intake-v1',status,reported_month:periodOk?requestedMonth:null,checks,missing_items:missing,row_count:table.rows.length,covered_locations:locations.filter(location=>INTAKE_LOCATIONS.includes(location as typeof INTAKE_LOCATIONS[number])),canonical_fields:[...new Set(table.headers)],...(missingAmounts.length?{missing_amounts:missingAmounts}:{}),ai_status:'not_requested'};
}
/** An unchanged reviewed fixed baseline is a reference, never a newly dated monthly actual. */
export function reviewFixedBaseline(table:ParsedTable,sourceHash:string,baseline:Record<string,unknown>|undefined):ReviewResult|null {
 if(!baseline||baseline.source_sha256!==sourceHash||baseline.cost_basis!=='fixed_monthly_baseline'||baseline.cadence!=='monthly'||typeof baseline.basis_note!=='string'||!baseline.basis_note.trim()||typeof baseline.basis_confirmed_at!=='string'||!Number.isFinite(Date.parse(baseline.basis_confirmed_at))||typeof baseline.revision_id!=='string'||!Array.isArray(baseline.overhead_rows)||baseline.overhead_rows.length!==140||table.rows.length!==140||table.blockedFields.length)return null;
 const amounts=new Map<string,number|null>();const missing:NonNullable<ReviewResult['missing_amounts']>=[];
 for(const raw of baseline.overhead_rows){if(!raw||typeof raw!=='object')return null;const row=raw as Record<string,unknown>;if(!INTAKE_LOCATIONS.includes(row.location as typeof INTAKE_LOCATIONS[number])||!INTAKE_EXPENSE_CATEGORIES.includes(row.category as typeof INTAKE_EXPENSE_CATEGORIES[number]))return null;const key=JSON.stringify([row.location,row.category]);if(amounts.has(key))return null;const value=row.amount===null?null:cents(String(row.amount));if(row.amount!==null&&value===null)return null;amounts.set(key,value);if(row.amount===null)missing.push({location:String(row.location),category:String(row.category),...(typeof row.sourceCell==='string'&&/^[A-Z]{1,3}[1-9][0-9]{0,4}$/.test(row.sourceCell)?{source_cell:row.sourceCell}:{})});}
 const seen=new Set<string>();for(const row of table.rows){const key=JSON.stringify([row.location,row.expense_category]);if(seen.has(key)||!amounts.has(key))return null;seen.add(key);const value=row.amount===null||row.amount===''?null:cents(row.amount);if(row.amount!==null&&row.amount!==''&&value===null||value!==amounts.get(key))return null;}
 const examples=missing.slice(0,5).map(row=>`${row.location} / ${row.category}${row.source_cell?` (${row.source_cell})`:''}`).join('; ');
 const gapMessage=missing.length?`${missing.length} overhead amounts remain blank: ${examples}${missing.length>5?`; and ${missing.length-5} more`:''}. Confirm each amount or mark it not applicable; blanks remain unknown.`:'All amounts in this fixed reference are supplied.';
 const reconciliation='This unchanged fixed-cost reference is already retained. Complete operating/shared costs and payroll still need their own reconciled monthly sources before profit can be reported.';
 const checks:ReviewCheck[]=[{key:'document_type',passed:true,message:'The uploaded bytes and all 140 source cells match the reviewed overhead baseline.'},{key:'reporting_period',passed:true,message:'The owner approved this exact source as fixed each month until changed. No new source month is required or inferred.'},{key:'required_fields',passed:true,message:'The reviewed 140-cell location/category matrix is present.'},{key:'row_values',passed:missing.length===0,message:gapMessage},{key:'location_coverage',passed:true,message:'All seven locations are retained in the existing baseline.'},{key:'reconciliation',passed:false,message:reconciliation},{key:'privacy',passed:true,message:'This is the unchanged reviewed aggregate cost source; no blocked identifiers were detected.'}];
 return{validator_version:'cheshire-intake-v1',status:'incomplete',reported_month:null,reference_basis:'fixed_monthly_baseline',checks,missing_items:[...(missing.length?[gapMessage]:[]),reconciliation],row_count:140,covered_locations:[...INTAKE_LOCATIONS],canonical_fields:INTAKE_REQUIREMENTS.find(item=>item.id==='overhead')!.fields,missing_amounts:missing,ai_status:'not_requested'};
}
export function hasCompletionEvidence(document:IntakeDocument,month:string){
 const review=document.validation;
 return document.status==='complete'&&document.requested_month===month&&document.reported_month===month&&review?.validator_version==='cheshire-intake-v1'&&review.status==='complete'&&review.reported_month===month&&review.missing_items.length===0&&REQUIRED_CHECKS.every(key=>review.checks.filter(check=>check.key===key&&check.passed).length===1);
}
/** AI sees only canonical metadata and validation outcomes, never row values or original files. */
export function sanitizedAiSummary(review:ReviewResult,sourceType:SourceType){
 const requirement=INTAKE_REQUIREMENTS.find(item=>item.id===sourceType);const allowed=new Set([...(requirement?.fields??[]),...(requirement?.optionalFields??[])]);
 return {source_type:sourceType,validator_version:review.validator_version,status:review.status,canonical_fields:review.canonical_fields.filter(field=>allowed.has(field)),required_fields:[...allowed],checks:review.checks.map(check=>({key:check.key,passed:check.passed})),row_count:review.row_count,covered_location_count:review.covered_locations.length};
}

