import test from 'node:test';import assert from 'node:assert/strict';
import {handleIntake,sha256} from '../supabase/functions/_shared/cheshire-intake-service.ts';
import {MAPPING_VERSION,recognitionSummary,inspectReportUpload} from '../supabase/functions/_shared/cheshire-report-mapping.ts';
import {INTAKE_LOCATIONS,REQUIRED_CHECKS} from '../supabase/functions/_shared/cheshire-intake.ts';
const USER='11111111-1111-4111-8111-111111111111',DOC='22222222-2222-4222-8222-222222222222',MANIFEST='33333333-3333-4333-8333-333333333333',REV='44444444-4444-4444-8444-444444444444';
const bytes=new TextEncoder().encode('PRIVATE_HEADER_CYCLE,office,program,income,report_total,currency\n'+INTAKE_LOCATIONS.map(l=>`2026-09,${l},PRIVATE_VALUE,1,7,USD`).join('\n')),hash=await sha256(bytes);
const mapping={version:MAPPING_VERSION,source_sha256:hash,source_type:'cash_programs',header_row:1,columns:['reporting_month','location','program','income','report_total','currency'],confirmed:true};
const env={SUPABASE_URL:'https://synthetic.invalid',SUPABASE_SERVICE_ROLE_KEY:'mock-service',HF_TOKEN:'mock-ai'};
const reply=(data,status=200)=>new Response(JSON.stringify(data),{status});
const review={operation:'review',document_id:DOC,expected_sha256:hash,mapping};
function fixture(options={}){let row={id:DOC,source_type:'cash_programs',requested_month:'2026-09-01',reported_month:null,uploaded_by:USER,file_name:'PRIVATE_FILENAME.csv',content_sha256:hash,byte_size:bytes.length,mime_type:'text/csv',storage_path:`${USER}/${DOC}/source.csv`,source_origin:'portal_upload',status:'uploading',validation:null,validation_scope:null,validation_dependencies:{},review_started_at:null,...options.row};const calls=[];let final;
 const fetcher=async(input,init={})=>{const url=new URL(String(input)),body=init.body?JSON.parse(init.body):null;calls.push({url:String(url),method:init.method??'GET',body});
  if(url.pathname==='/auth/v1/user')return reply({id:USER,email:'synthetic@example.test',email_confirmed_at:'2026-01-01'});
  if(url.pathname==='/rest/v1/cheshire_finance_reader')return reply(options.deny?[]:[{user_id:USER}]);
  if(url.pathname==='/rest/v1/cheshire_portal_member')return reply([{email:'synthetic@example.test'}]);
  if(url.pathname==='/rest/v1/cheshire_intake_settings')return reply([{ai_enabled:options.ai===true,ai_monthly_limit:5}]);
  if(url.pathname==='/rest/v1/rpc/reserve_cheshire_intake_ai_call')return reply(!options.capped);
  if(url.hostname==='router.huggingface.co')return reply({choices:[{message:{content:options.aiReply??'{"source_types":["cash_programs"]}'}}]});
  if(url.pathname==='/rest/v1/cheshire_intake_document'){
   if(init.method==='PATCH'){const revision=url.searchParams.get('review_revision');if(revision&&(revision==='is.null'?row.review_revision!=null:revision!=='eq.'+row.review_revision))return reply([]);row={...row,...body};return reply([row]);}
   if(url.searchParams.get('source_type')?.startsWith('in.'))return reply([{id:MANIFEST,source_type:'coverage_manifest',requested_month:'2026-09-01',reported_month:'2026-09-01',content_sha256:'b'.repeat(64),status:'complete',review_revision:REV,review_token:REV,validation:{validator_version:'cheshire-intake-v1',status:'complete',checks:REQUIRED_CHECKS.map(key=>({key,passed:true})),missing_items:[]},validation_scope:{expectedProvidersBySource:{cash_programs:Object.fromEntries(INTAKE_LOCATIONS.map(l=>[l,['PRIVATE_VALUE']]))}}}]);
   return reply([row]);
  }
  if(url.pathname.startsWith('/storage/')){if(options.advanceRevisionOnStorage)row={...row,review_revision:options.advanceRevisionOnStorage,validation:{mapping:{...mapping,columns:[...mapping.columns].reverse()}}};return new Response(options.bytes??bytes);}
  if(url.pathname==='/rest/v1/rpc/finalize_cheshire_intake_review'){final=body;row={...row,status:body.p_validation.status,validation:body.p_validation,review_revision:row.review_token};return reply([row]);}
  throw new Error('Unexpected mock URL '+url);
 };
 return {calls,get row(){return row;},get final(){return final;},async run(body=review){const res=await handleIntake(new Request('https://edge.invalid',{method:'POST',headers:{Authorization:'Bearer mock','Content-Type':'application/json'},body:JSON.stringify(body)}),env,fetcher);return {status:res.status,data:await res.json()};}};
}
test('server reparses original, records actor/hash mapping provenance and normalizes under existing dependencies',async()=>{const f=fixture();const r=await f.run();assert.equal(r.status,200);assert.equal(f.final.p_validation.status,'complete');assert.equal(f.final.p_rows.length,7);assert.equal(f.final.p_validation.mapping.confirmed_by,USER);assert.equal(f.final.p_validation.mapping.source_sha256,hash);assert.equal(f.final.p_dependency_revisions.coverage_manifest,REV);assert(!('review_token' in r.data.document));assert(!('validation_scope' in r.data.document));});
test('rereview reuses confirmed mapping and its original provenance but rotates review revision',async()=>{const first=fixture();await first.run();const saved=structuredClone(first.row);const second=fixture({row:saved});const r=await second.run({operation:'review',document_id:DOC,expected_sha256:hash});assert.equal(r.status,200);assert.deepEqual(second.final.p_validation.mapping,saved.validation.mapping);assert.notEqual(second.row.review_revision,saved.review_revision);});
test('invalid hash/source/duplicate mapping is rejected before review claim or metric mutation',async()=>{for(const patch of [{source_sha256:'f'.repeat(64)},{source_type:'payroll'},{columns:['income','income']}]){const f=fixture();const r=await f.run({...review,mapping:{...mapping,...patch}});assert.equal(r.status,400);assert(!f.calls.some(c=>c.method==='PATCH'||c.url.includes('finalize')));}});
test('stored bytes must still match hash before mapping can be used',async()=>{const f=fixture({bytes:new Uint8Array([1,2,3])});assert.equal((await f.run()).status,422);assert.equal(f.final,undefined);});
test('recognition sends only validated canonical codes and counts, no source/hash/user/headers/values',async()=>{const f=fixture({ai:true});const summary=recognitionSummary(inspectReportUpload(bytes,'PRIVATE_FILENAME.csv','text/csv'));const r=await f.run({operation:'recognize',content_sha256:hash,summary});assert.equal(r.status,200);assert.deepEqual(r.data.source_types,['cash_programs']);const ai=f.calls.find(c=>c.url.includes('huggingface'));assert(ai);const payload=JSON.stringify(ai.body);for(const marker of ['PRIVATE',hash,USER])assert(!payload.includes(marker));assert(!f.calls.some(c=>c.url.includes('/storage/')||c.method==='PATCH'||c.url.includes('finalize')));});
test('recognition rejects raw fields before any provider transmission',async()=>{for(const extra of [{headers:['PRIVATE']},{canonical_fields:['PRIVATE']},{row_count:99999}]){const f=fixture({ai:true});const r=await f.run({operation:'recognize',content_sha256:hash,summary:{candidate_source_types:['cash_programs'],canonical_fields:['income'],row_count:7,...extra}});assert.equal(r.status,400);assert(!f.calls.some(c=>c.url.includes('huggingface')||c.url.includes('reserve_')));}});
test('AI cannot return unoffered type, extra prose, completion authority or duplicate codes',async()=>{for(const aiReply of ['{"source_types":["payroll"]}','{"source_types":["cash_programs"],"status":"complete"}','{"source_types":["cash_programs","cash_programs"]}','{"source_types":[],"note":"PRIVATE"}']){const f=fixture({ai:true,aiReply});const r=await f.run({operation:'recognize',content_sha256:hash,summary:{candidate_source_types:['cash_programs'],canonical_fields:['income'],row_count:7}});assert.equal(r.data.ai_status,'unavailable');assert.deepEqual(r.data.source_types,[]);}});
test('AI cap, disabled AI and access denial fail closed without changing originals',async()=>{for(const options of [{ai:true,capped:true},{ai:false},{ai:true,deny:true}]){const f=fixture(options);const r=await f.run({operation:'recognize',content_sha256:hash,summary:{candidate_source_types:['cash_programs'],canonical_fields:['income'],row_count:7}});assert.equal(r.status,options.deny?403:200);assert(!f.calls.some(c=>c.url.includes('huggingface')||c.method==='PATCH'));}});

test('new submitted mapping cannot be silently ignored by an in-progress review',async()=>{const f=fixture({row:{status:'reviewing',review_started_at:new Date().toISOString()}});const r=await f.run();assert.equal(r.status,409);assert.equal(r.data.code,'mapping_review_in_progress');assert.match(r.data.error,/mapping has not been saved/);assert(!f.calls.some(c=>c.url.includes('/storage/')||c.method==='PATCH'));});
test('delayed same-status claim cannot overwrite a newer completed mapping revision',async()=>{for(const oldRevision of [null,REV]){const newer='55555555-5555-4555-8555-555555555555';const f=fixture({row:{status:'complete',review_revision:oldRevision},advanceRevisionOnStorage:newer});const r=await f.run();assert.equal(r.status,409);assert.equal(r.data.code,'review_race');assert.equal(f.final,undefined);assert.equal(f.row.review_revision,newer);assert.deepEqual(f.row.validation.mapping.columns,[...mapping.columns].reverse());const claim=f.calls.find(c=>c.method==='PATCH');assert.equal(new URL(claim.url).searchParams.get('review_revision'),oldRevision?'eq.'+oldRevision:'is.null');}});

test('explicit null mapping cannot rewrite earlier confirmation provenance',async()=>{const saved={...mapping,confirmed_by:USER,confirmed_at:'2026-09-01T00:00:00Z'};const f=fixture({row:{status:'complete',validation:{mapping:saved}}});const r=await f.run({...review,mapping:null});assert.equal(r.status,400);assert.equal(f.final,undefined);assert.equal(f.row.validation.mapping.confirmed_at,saved.confirmed_at);assert(!f.calls.some(c=>c.method==='PATCH'));});
