import test from'node:test';import assert from'node:assert/strict';import{PGlite}from'@electric-sql/pglite';
import{prepareCumulativeDocuments,cumulativeImportSQL}from'../scripts/prepare-cumulative-import.mjs';
import{cumulativeFixture}from'./helpers/cumulative-fixture.mjs';
test('private cumulative import is atomic, idempotent, guarded and cannot overwrite an existing source',async()=>{
 const db=new PGlite();try{await db.exec(`create table public.cheshire_intake_document(id uuid primary key,source_type text,requested_month date,reported_month date,file_name text,content_sha256 text,byte_size integer,mime_type text,storage_path text,source_origin text,status text,no_phi_attested_at timestamptz,source_period_label text,source_scope_label text,figure_unlocked text,reviewed_at timestamptz,review_revision uuid,validation jsonb);create unique index dedup on public.cheshire_intake_document(source_type,coalesce(requested_month,date '0001-01-01'),content_sha256);`);
 const reports=['insurance_service_cohort','provider_posted_payments','facility_reported_activity'].map((kind,index)=>{const report=cumulativeFixture(kind);report.source.sha256=String(index+1).repeat(64);if(index===0)report.warnings.push('Literal hostile label: $cheshire_guard$; drop table never_execute; --');return report});const documents=prepareCumulativeDocuments(reports);const sql=cumulativeImportSQL(documents);await db.exec(sql);let rows=(await db.query('select * from public.cheshire_intake_document order by id')).rows;assert.equal(rows.length,3);assert.ok(rows.every(row=>row.status==='incomplete'&&row.requested_month===null&&row.reported_month===null&&row.storage_path===null&&row.source_origin==='existing_source'));const ids=rows.map(row=>row.id);
 await db.exec(cumulativeImportSQL(prepareCumulativeDocuments(reports)));assert.deepEqual((await db.query('select id from public.cheshire_intake_document order by id')).rows.map(row=>row.id),ids,'replay is a no-op even with new prepared ids');
 const changed=structuredClone(reports);changed[0].warnings.push('Changed evidence');await assert.rejects(db.exec(cumulativeImportSQL(prepareCumulativeDocuments(changed))),/Existing source differs/);await db.exec('rollback');assert.equal((await db.query('select count(*)::integer as n from public.cheshire_intake_document')).rows[0].n,3);
 const newReports=structuredClone(reports);newReports.forEach((r,i)=>r.source.sha256=String(i+4).repeat(64));const corrupt=cumulativeImportSQL(prepareCumulativeDocuments(newReports)).replace('"insurance_payments":12000','"insurance_payments":12001');await assert.rejects(db.exec(corrupt),/Leaf payment arithmetic/);await db.exec('rollback');assert.equal((await db.query('select count(*)::integer as n from public.cheshire_intake_document')).rows[0].n,3,'failed bundle inserts nothing');
 assert.doesNotMatch(sql,/create policy|grant |alter table|update public\.cheshire_intake_document|delete from/i);
 }finally{await db.close()}
});
