// Synthetic relationship attacks stay local; no client data or network.
import test from 'node:test';
import assert from 'node:assert/strict';
import {zipSync,strToU8,strFromU8} from 'fflate';
import {xlsxParts,NS,REL,PKG,CT,sheetType,stringsType} from './helpers/xlsx-fixture.mjs';
import {parseXlsx} from '../supabase/functions/_shared/cheshire-files.ts';
import {INTAKE_LOCATIONS,INTAKE_REQUIREMENTS,validateTable} from '../supabase/functions/_shared/cheshire-intake.ts';
const rows=[INTAKE_REQUIREMENTS.find(item=>item.id==='cash_programs').fields,...INTAKE_LOCATIONS.map(location=>['2026-09',location,'synthetic-program','0','0'])];
const xml=`<worksheet xmlns="${NS}"><sheetData>`+rows.map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>`<c r="${String.fromCharCode(65+c)}${r+1}" t="inlineStr"><is><t>${value}</t></is></c>`).join('')}</row>`).join('')+'</sheetData></worksheet>';
const parts=()=>xlsxParts(xml);
const update=(files,name,fn)=>{files[name]=strToU8(fn(strFromU8(files[name])));};
const rename=(files,from,to)=>{files[to]=files[from];delete files[from];update(files,'xl/_rels/workbook.xml.rels',text=>text.replace(from.slice(3),to.slice(3)));update(files,'[Content_Types].xml',text=>text.replace(from,to));};
const review=files=>validateTable(parseXlsx(zipSync(files),'cash_programs'),'cash_programs','2026-09',{expectedProvidersBySource:{cash_programs:Object.fromEntries(INTAKE_LOCATIONS.map(location=>[location,['synthetic-program']]))}});
const reject=(name,mutate)=>test(name,()=>{const files=parts();mutate(files);assert.throws(()=>review(files),/identity|archive|worksheet|review|No supported monthly aggregate/i);});
test('ordinary and nonstandard worksheet names resolve to the declared source',()=>{assert.equal(review(parts()).status,'complete');const files=parts();rename(files,'xl/worksheets/sheet1.xml','xl/worksheets/data.xml');assert.equal(review(files).status,'complete');});
reject('orphan template is not substituted for the displayed nonstandard worksheet',files=>{rename(files,'xl/worksheets/sheet1.xml','xl/worksheets/data.xml');files['xl/worksheets/data.xml']=strToU8(`<worksheet xmlns="${NS}"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Actual visible content</t></is></c></row></sheetData></worksheet>`);files['xl/worksheets/sheet1.xml']=strToU8(xml);});
reject('unreferenced worksheet declared outside standard directory is rejected',files=>{files['xl/orphan.xml']=strToU8(xml);update(files,'[Content_Types].xml',text=>text.replace('</Types>',`<Override PartName="/xl/orphan.xml" ContentType="${sheetType}"/></Types>`));});
for(const state of ['hidden','veryHidden'])reject(`${state} worksheets require explicit manual review`,files=>update(files,'xl/workbook.xml',text=>text.replace('sheetId="1"',`sheetId="1" state="${state}"`)));
reject('missing declared worksheet is rejected',files=>delete files['xl/worksheets/sheet1.xml']);
reject('missing workbook relationships are rejected',files=>delete files['xl/_rels/workbook.xml.rels']);
reject('unconsumed worksheet relationship is rejected',files=>update(files,'xl/_rels/workbook.xml.rels',text=>text.replace('</Relationships>',`<Relationship Id="orphan" Type="${REL}/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`)));
reject('duplicate relationship identifiers are rejected',files=>update(files,'xl/_rels/workbook.xml.rels',text=>text.replace('</Relationships>',`<Relationship Id="sheet1" Type="${REL}/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`)));
reject('duplicate sheet targets are rejected',files=>{update(files,'xl/workbook.xml',text=>text.replace('</sheets>','<sheet name="Duplicate" sheetId="2" r:id="sheet2"/></sheets>'));update(files,'xl/_rels/workbook.xml.rels',text=>text.replace('</Relationships>',`<Relationship Id="sheet2" Type="${REL}/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`));});
reject('chartsheet and other nonworksheet declared sheets are rejected',files=>update(files,'xl/_rels/workbook.xml.rels',text=>text.replace('/worksheet"','/chartsheet"')));
for(const target of ['https://synthetic.invalid/data.xml','../../escape.xml','worksheets/data.xml#fragment','worksheets/%73heet1.xml'])reject(`unsafe target ${target} is rejected`,files=>update(files,'xl/_rels/workbook.xml.rels',text=>text.replace('worksheets/sheet1.xml',target)));
reject('external target mode with XML whitespace cannot bypass inspection',files=>update(files,'xl/_rels/workbook.xml.rels',text=>text.replace('Target=',"TargetMode = 'External' Target=")));
reject('wrong package officeDocument does not allow an orphan workbook',files=>update(files,'_rels/.rels',text=>text.replace('xl/workbook.xml','xl/other.xml')));
reject('commented-out sheet declarations cannot supply identity',files=>update(files,'xl/workbook.xml',text=>text.replace(/<sheet\s[^>]*\/>/,'<!-- $& -->')));
reject('wrong relationship namespace cannot impersonate sheet identity',files=>update(files,'xl/workbook.xml',text=>text.replace(`xmlns:r="${REL}"`,'xmlns:r="urn:unsupported"')));
reject('trailing malformed XML is rejected',files=>update(files,'xl/workbook.xml',text=>text+'</extra>'));
test('namespaced metadata and package-absolute targets resolve without guessing',()=>{const files=parts();update(files,'xl/_rels/workbook.xml.rels',text=>text.replace(`xmlns="${PKG}"`,`xmlns:p="${PKG}"`).replace(/<(\/?)(Relationships|Relationship)\b/g,'<$1p:$2').replace('Target="worksheets/sheet1.xml"','Target="/xl/worksheets/sheet1.xml"'));assert.equal(review(files).status,'complete');});
test('nonstandard shared string part uses its declared relationship',()=>{const files=parts();files['xl/values.xml']=strToU8('<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><si><t>0</t></si></sst>');update(files,'xl/worksheets/sheet1.xml',text=>text.replace('<c r="D2" t="inlineStr"><is><t>0</t></is></c>','<c r="D2" t="s"><v>0</v></c>'));update(files,'xl/_rels/workbook.xml.rels',text=>text.replace('</Relationships>',`<Relationship Id="strings" Type="${REL}/sharedStrings" Target="values.xml"/></Relationships>`));update(files,'[Content_Types].xml',text=>text.replace('</Types>',`<Override PartName="/xl/values.xml" ContentType="${stringsType}"/></Types>`));assert.equal(review(files).status,'complete');});
reject('orphan conventional shared strings cannot supply cell values',files=>{files['xl/sharedStrings.xml']=strToU8('<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><si><t>0</t></si></sst>');});
// Prevent accidental weakening of the metadata fixture itself.
test('fixture has valid package content type namespace',()=>assert.ok(strFromU8(parts()['[Content_Types].xml']).includes(CT)));
reject('comment-only template is never substituted for visible worksheet data',files=>update(files,'xl/worksheets/sheet1.xml',()=>`<worksheet xmlns="${NS}"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Actual visible content</t></is></c></row></sheetData><!-- ${xml} --></worksheet>`));
test('prefixed spreadsheet tags are consumed, including restricted fields on another sheet',()=>{
 const second=`<p:worksheet xmlns:p="${NS}"><p:sheetData><p:row r="1"><p:c r="A1" t="inlineStr"><p:is><p:t>patient_name</p:t></p:is></p:c></p:row></p:sheetData></p:worksheet>`;
 assert.throws(()=>review(xlsxParts(xml,{'xl/worksheets/sheet2.xml':second})),/Multiple populated worksheets/);assert.equal(review(xlsxParts(second)).status,'quarantined');
 const files=parts();update(files,'xl/worksheets/sheet1.xml',text=>text.replace(`xmlns="${NS}"`,`xmlns:p="${NS}"`).replace(/<(\/?)(worksheet|sheetData|row|c|is|t)\b/g,'<$1p:$2'));assert.equal(review(files).status,'complete');
});
reject('a second populated prefixed worksheet cannot be silently dropped',files=>{
 files['xl/worksheets/sheet2.xml']=strToU8(`<p:worksheet xmlns:p="${NS}"><p:sheetData><p:row r="1"><p:c r="A1" t="inlineStr"><p:is><p:t>Additional source values</p:t></p:is></p:c></p:row></p:sheetData></p:worksheet>`);
 update(files,'xl/workbook.xml',text=>text.replace('</sheets>','<sheet name="Other" sheetId="2" r:id="sheet2"/></sheets>'));update(files,'xl/_rels/workbook.xml.rels',text=>text.replace('</Relationships>',`<Relationship Id="sheet2" Type="${REL}/worksheet" Target="worksheets/sheet2.xml"/></Relationships>`));update(files,'[Content_Types].xml',text=>text.replace('</Types>',`<Override PartName="/xl/worksheets/sheet2.xml" ContentType="${sheetType}"/></Types>`));
});
reject('duplicate financial cells are not last-write-wins',files=>update(files,'xl/worksheets/sheet1.xml',text=>text.replace('<row r="2">','<row r="2"><c r="D2"><v>999</v></c>')));
reject('duplicate value elements are ambiguous',files=>update(files,'xl/worksheets/sheet1.xml',text=>text.replace('<is><t>0</t></is>','<v>1</v><v>0</v>')));
reject('multiple plain text nodes cannot concatenate into another financial number',files=>update(files,'xl/worksheets/sheet1.xml',text=>text.replace('<t>0</t>','<t>1</t><t>0</t>')));
reject('cells outside sheetData rows are not consumed as visible facts',files=>update(files,'xl/worksheets/sheet1.xml',text=>text.replace('</sheetData>','</sheetData><c r="A999"><v>1</v></c>')));
reject('unknown worksheet-cell child content fails closed',files=>update(files,'xl/worksheets/sheet1.xml',text=>text.replace('<is><t>0</t></is>','<unsupported><v>0</v></unsupported>')));
reject('hidden financial rows require manual review',files=>update(files,'xl/worksheets/sheet1.xml',text=>text.replace('<row r="2">','<row r="2" hidden="1">')));
test('attribute whitespace and XML namespace aliases preserve actual cell values',()=>{const files=parts();update(files,'xl/worksheets/sheet1.xml',text=>text.replaceAll(' r="',' r = "').replaceAll(' t="',' t = "'));assert.equal(review(files).status,'complete');});
test('shared-string comments never shift cell string indexes',()=>{const files=xlsxParts(xml,{'xl/sharedStrings.xml':`<sst xmlns="${NS}"><!-- <si><t>999</t></si> --><si><t>0</t></si></sst>`});update(files,'xl/worksheets/sheet1.xml',text=>text.replace('<c r="D2" t="inlineStr"><is><t>0</t></is></c>','<c r="D2" t="s"><v>0</v></c>'));assert.equal(review(files).status,'complete');});
reject('XML construction rejects excessive complexity before allocating a full cell tree',files=>update(files,'xl/worksheets/sheet1.xml',()=>`<worksheet xmlns="${NS}"><sheetData>${Array.from({length:8500},(_,i)=>`<row r="${i+1}"><c r="A${i+1}"><v>0</v></c></row>`).join('')}</sheetData></worksheet>`));
reject('excessive XML attributes cannot inflate namespace or attribute maps',files=>update(files,'xl/workbook.xml',text=>text.replace('<workbook ',`<workbook ${Array.from({length:65},(_,i)=>`attribute${i}="value"`).join(' ')} `)));
reject('oversized namespace URIs cannot amplify inherited QName allocation',files=>update(files,'xl/workbook.xml',text=>text.replace('<workbook ',`<workbook xmlns:oversized="urn:${'a'.repeat(1000)}" `)));
reject('oversized encoded text is bounded before entity decoding',files=>update(files,'xl/worksheets/sheet1.xml',text=>text.replace('<t>0</t>',`<t>${'&amp;'.repeat(50000)}</t>`)));
test('the XML construction budget is cumulative across otherwise empty worksheets',()=>{const blank=`<worksheet xmlns="${NS}"><sheetData>${Array.from({length:6500},(_,i)=>`<row r="${i+1}"><c r="A${i+1}"/></row>`).join('')}</sheetData></worksheet>`;assert.throws(()=>review(xlsxParts(blank,{'xl/worksheets/sheet2.xml':blank})),/supported review complexity/);});
test('a formula-only worksheet without cached values is not discarded as empty',()=>{const formula=`<worksheet xmlns="${NS}"><sheetData><row r="1"><c r="A1"><f>"Additional financial content"</f><v/></c></row></sheetData></worksheet>`;assert.throws(()=>review(xlsxParts(xml,{'xl/worksheets/sheet2.xml':formula})),/formula-bearing worksheet/);});
