import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,rm}from'node:fs/promises';import{fileURLToPath,pathToFileURL}from'node:url';import{build}from'esbuild';import React from'react';import{create,act}from'react-test-renderer';
test('YTD summary uses one source family, keeps unknown profit, and exposes source detail without category subtitles',async()=>{
 const cache=fileURLToPath(new URL('../node_modules/.cache/',import.meta.url));await mkdir(cache,{recursive:true});const dir=await mkdtemp(cache+'cumulative-ui-');let renderer;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
 try{await build({stdin:{contents:`import React from'react';import{IntakeContext}from'./src/cheshire/intakeContext';import{CheshireFinanceDashboardView}from'./src/cheshire/CheshireFinanceDashboardView';import{cumulativeFixture}from'./tests/helpers/cumulative-fixture.mjs';export function Harness({month='2026-10'}){const reports=['insurance_service_cohort','provider_posted_payments','facility_reported_activity'].map(cumulativeFixture);const documents=reports.map((r,i)=>({id:String(i),source_type:'insurance_revenue',content_sha256:r.source.sha256,status:'incomplete',source_origin:'existing_source',requested_month:null,reported_month:null,storage_path:null,created_at:'2026-10-02T00:00:00Z',validation:{validator_version:'source-audit-v1',cumulative_report:r,missing_items:[],reported_metrics:[],checks:[],covered_locations:[],canonical_fields:[]}}));return <IntakeContext.Provider value={{month,documents,state:'ready',busy:false,selected:'coverage_manifest',setSelected:()=>{},setMonth:()=>{},refresh:()=>{},referenceSnapshot:null}}><CheshireFinanceDashboardView snapshot={null} state="empty" onRefresh={()=>{}}/></IntakeContext.Provider>}`,resolveDir:fileURLToPath(new URL('../',import.meta.url)),loader:'tsx'},outfile:dir+'/test.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'},define:{'import.meta.env':'{}'},logLevel:'silent',plugins:[{name:'mock-period',setup(b){b.onResolve({filter:/useProfitabilityPeriod$/},()=>({path:'period',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:`import{useIntake}from'${fileURLToPath(new URL('../src/cheshire/intakeContext.ts',import.meta.url))}';export function useProfitabilityPeriod(mode,scope){const i=useIntake();return{months:[i.month],scope,responses:{},categories:[],failedMonths:[],mapError:false,state:'ready'}}`,loader:'ts',resolveDir:fileURLToPath(new URL('../',import.meta.url))}))}}]});const{Harness}=await import(pathToFileURL(dir+'/test.mjs'));await act(async()=>{renderer=create(React.createElement(Harness));});
 const totals=()=>renderer.root.findByProps({className:'csd-totals'});assert.deepEqual(totals().findAllByType('strong').map(n=>n.children.join('')),['$140.00','—','—']);assert.equal(totals().findAllByType('span')[0].children.join(''),'Reported payments');assert.equal(totals().findAllByType('p')[0].children.join(''),'Need Data');assert.ok(totals().findAllByType('small')[0].children.filter(n=>typeof n==='string').join('').includes('date basis unconfirmed'));
 const categories=renderer.root.findAllByType('details').filter(item=>String(item.props.className).startsWith('csd-category '));assert.ok(categories.every(item=>item.findAllByType('summary')[0].findAllByType('p').length===0));const reports=renderer.root.findAllByProps({className:'ccr-report'});assert.equal(reports.length,3);assert.ok(reports.every(item=>!item.props.open));
 await act(async()=>renderer.root.findAllByType('button').find(button=>button.children.join('')==='MTD').props.onClick());assert.equal(renderer.root.findAllByProps({className:'ccr-report'}).length,0);assert.deepEqual(totals().findAllByType('strong').map(n=>n.children.join('')),['—','—','—']);await act(async()=>renderer.root.findAllByType('button').find(button=>button.children.join('')==='YTD').props.onClick());await act(async()=>renderer.update(React.createElement(Harness,{month:'2026-09'})));assert.equal(renderer.root.findAllByProps({className:'ccr-report'}).length,0);assert.equal(totals().findAllByType('strong')[0].children.join(''),'—');
 }finally{if(renderer)await act(async()=>renderer.unmount());await rm(dir,{recursive:true,force:true});delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
});
