import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,rm}from'node:fs/promises';import{fileURLToPath,pathToFileURL}from'node:url';import{build}from'esbuild';import React from'react';import{create,act}from'react-test-renderer';
const payload=(month,location)=>({month,location,sources:[],blocked:[],profit:{available:false,reason:'Missing accounting basis'},accounting_request:'Confirm accounting basis'});
test('period requests are scope bounded, cache current month, and clear stale month/location/review/identity evidence',async()=>{
 const cache=fileURLToPath(new URL('../node_modules/.cache/',import.meta.url));await mkdir(cache,{recursive:true});const dir=await mkdtemp(cache+'period-lifecycle-');globalThis.IS_REACT_ACT_ENVIRONMENT=true;let renderer;const requests=[];let active=0,max=0;
 globalThis.__periodInvoke=(_name,options)=>new Promise(resolve=>{active++;max=Math.max(max,active);requests.push({options,resolve:value=>{active--;resolve(value);}});});
 try{await build({stdin:{contents:`import React from'react';import{IntakeContext}from'./src/cheshire/intakeContext';import{useProfitabilityPeriod}from'./src/cheshire/useProfitabilityPeriod';function Read({mode,scope}){return <pre>{JSON.stringify(useProfitabilityPeriod(mode,scope))}</pre>}export function Harness({month='2026-03',scope='all',mode='mtd',state='ready',busy=false,actor='one',documents=[]}){return <IntakeContext.Provider key={actor} value={{month,state,busy,documents,referenceSnapshot:null}}><Read mode={mode} scope={scope}/></IntakeContext.Provider>}`,resolveDir:fileURLToPath(new URL('../',import.meta.url)),loader:'tsx'},outfile:dir+'/test.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',logLevel:'silent',plugins:[{name:'private-client',setup(b){b.onResolve({filter:/cheshireSupabase$/},()=>({path:'client',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:`export const cheshireSupabase={functions:{invoke:(...args)=>globalThis.__periodInvoke(...args)},from:()=>({select:()=>({order:()=>Promise.resolve({data:[],error:null})})})}`,loader:'js'}));}}]});
 const{Harness}=await import(pathToFileURL(dir+'/test.mjs'));const read=()=>JSON.parse(renderer.toJSON().children[0]);const update=async props=>act(async()=>renderer.update(React.createElement(Harness,props)));const finish=async(index,wrong=false)=>act(async()=>{const request=requests[index];request.resolve({data:{metrics:payload(wrong?'2025-01':request.options.body.month,request.options.body.location)},error:null});});
 await act(async()=>{renderer=create(React.createElement(Harness,{}));});assert.equal(requests.length,1);await finish(0);assert.equal(read().state,'ready');
 await update({mode:'ytd'});assert.equal(requests.length,3,'YTD reuses the current month and requests only January/February');assert.deepEqual(read().responses,{});await finish(1);await finish(2);assert.equal(Object.keys(read().responses).length,3);
 await update({mode:'ytd',scope:'Pool'});assert.equal(requests.length,6);assert.deepEqual(read().responses,{});await update({mode:'ytd',scope:'Orange'});assert.equal(requests.length,6,'new scope queues behind existing in-flight calls');await finish(3);await finish(4);await finish(5);assert.equal(requests.length,9);assert.deepEqual(read().responses,{});await finish(6);await finish(7);await finish(8);assert.equal(read().scope,'Orange');assert.equal(max,3);assert.equal(Object.keys(read().responses).length,3);
 await update({scope:'Orange',mode:'ytd',busy:true});assert.deepEqual(read().responses,{});await update({scope:'Orange',mode:'ytd'});assert.equal(requests.length,12);assert.deepEqual(read().responses,{});await finish(9);await finish(10,true);await finish(11);assert.equal(read().failedMonths.length,1);assert.equal(Object.keys(read().responses).length,2);
 await update({scope:'Orange',mode:'ytd',documents:[{id:'same',review_revision:'new'}]});assert.deepEqual(read().responses,{});await update({scope:'Orange',mode:'ytd',actor:'two',state:'no-access'});await finish(12);await finish(13);await finish(14);assert.deepEqual(read().responses,{});assert.deepEqual(read().categories,[]);
 }finally{if(renderer)await act(async()=>renderer.unmount());await rm(dir,{recursive:true,force:true});delete globalThis.__periodInvoke;delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
});
