import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,rm}from'node:fs/promises';import{fileURLToPath,pathToFileURL}from'node:url';import{build}from'esbuild';import React from'react';import{create,act}from'react-test-renderer';
test('clean navigation opens requests from the map, retains all groups and reopens after dismissal and history navigation',async()=>{
 const cache=fileURLToPath(new URL('../node_modules/.cache/',import.meta.url));await mkdir(cache,{recursive:true});const dir=await mkdtemp(cache+'source-navigation-');let renderer;const previousDocument=globalThis.document,previousDetails=globalThis.HTMLDetailsElement;globalThis.IS_REACT_ACT_ENVIRONMENT=true;globalThis.__onDashboard=false;let scrolled=0,focused=0,reviewFocus=0;
 globalThis.HTMLDetailsElement=class{open=false;querySelector(){return{focus:()=>focused++}}scrollIntoView(){scrolled++}};
 const disclosure=new globalThis.HTMLDetailsElement();globalThis.document={getElementById:id=>!globalThis.__onDashboard?null:id==='csd-source-review'?disclosure:id==='monthly-intake-review'?{focus:()=>reviewFocus++,scrollIntoView:()=>scrolled++}:id==='cheshire-financial-summary'?{scrollIntoView:()=>scrolled++}:null};
 try{await build({stdin:{contents:`import React,{useState,useLayoutEffect}from'react';import{MemoryRouter,Routes,Route,useNavigate,useLocation}from'react-router-dom';import{IntakeContext}from'./src/cheshire/intakeContext';import{CheshireMonthlyChecklist}from'./src/cheshire/CheshireMonthlyIntake';import{CheshirePortalNavigation}from'./src/cheshire/CheshirePortalNavigation';function Dashboard(){useLayoutEffect(()=>{globalThis.__onDashboard=true;return()=>{globalThis.__onDashboard=false}},[]);return <><h1>Dashboard</h1><CheshireMonthlyChecklist/></>}function History(){const n=useNavigate();const l=useLocation();return <><output>{l.pathname+l.hash}</output><button onClick={()=>n(-1)}>Back</button><button onClick={()=>n(1)}>Forward</button></>}export function Harness(){const[selected,setSelected]=useState('coverage_manifest');return <MemoryRouter initialEntries={['/cheshire/map']}><IntakeContext.Provider value={{month:'2026-10',setMonth:()=>{},selected,setSelected,documents:[],referenceSnapshot:null,state:'ready'}}><CheshirePortalNavigation/><History/><Routes><Route path="/cheshire/map" element={<h1>Map</h1>}/><Route path="/cheshire/dashboard" element={<Dashboard/>}/></Routes></IntakeContext.Provider></MemoryRouter>}`,resolveDir:fileURLToPath(new URL('../',import.meta.url)),loader:'tsx'},outfile:dir+'/test.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'},define:{'import.meta.env':'{}'},logLevel:'silent'});
 const{Harness}=await import(pathToFileURL(dir+'/test.mjs'));await act(async()=>{renderer=create(React.createElement(Harness));});
 const links=()=>renderer.root.findByType('nav').findAllByType('a');assert.deepEqual(links().map(link=>link.children.join('')),['Dashboard','Profitability map','Data requests']);assert.equal(renderer.root.findAllByProps({className:'cfi-checklist'}).length,0);
 const clickLink=async(label)=>{const event={button:0,defaultPrevented:false,preventDefault(){this.defaultPrevented=true}};await act(async()=>links().find(link=>link.children.join('')===label).props.onClick(event));};
 await clickLink('Data requests');assert.equal(globalThis.__onDashboard,true);assert.equal(disclosure.open,true);assert.ok(scrolled>0&&focused>0);assert.equal(links()[2].props['aria-current'],'page');assert.equal(links()[0].props['aria-current'],undefined);
 const requests=()=>renderer.root.findAllByType('button').filter(button=>String(button.props.className??'').startsWith('cfi-request '));assert.equal(requests().length,9);const source=requests().find(button=>button.findByType('strong').children.join('')==='Insurance payments');await act(async()=>source.props.onClick());assert.equal(source.props['aria-pressed'],true);assert.ok(reviewFocus>0);assert.ok(JSON.stringify(renderer.toJSON()).includes('Needed for profit: accounting definition'));
 disclosure.open=false;await clickLink('Data requests');assert.equal(disclosure.open,true);
 await clickLink('Dashboard');assert.equal(links()[0].props['aria-current'],'page');await act(async()=>renderer.root.findAllByType('button').find(button=>button.children.join('')==='Back').props.onClick());assert.equal(links()[2].props['aria-current'],'page');await act(async()=>renderer.root.findAllByType('button').find(button=>button.children.join('')==='Forward').props.onClick());assert.equal(links()[0].props['aria-current'],'page');assert.equal(source.props['aria-pressed'],true);
 }finally{if(renderer)await act(async()=>renderer.unmount());await rm(dir,{recursive:true,force:true});if(previousDocument===undefined)delete globalThis.document;else globalThis.document=previousDocument;if(previousDetails===undefined)delete globalThis.HTMLDetailsElement;else globalThis.HTMLDetailsElement=previousDetails;delete globalThis.__onDashboard;delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
});
