// Real local PostgreSQL engine with synthetic schemas/identities only. Never connects to Supabase.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { buildMonthlyChecklist,parseIntakeDocuments } from '../src/cheshire/intake.ts';
import { REQUIRED_CHECKS } from '../supabase/functions/_shared/cheshire-intake.ts';
const id='22222222-2222-2222-2222-222222222222',token='33333333-3333-3333-3333-333333333333',manifestId='44444444-4444-4444-4444-444444444444',manifestToken='55555555-5555-5555-5555-555555555555',manifestRevision='aaaaaaaa-1111-4111-8111-111111111111',hash='a'.repeat(64);
const review={validator_version:'cheshire-intake-v1',status:'complete',reported_month:'2026-09',missing_items:[],covered_locations:[],canonical_fields:[],row_count:1,checks:REQUIRED_CHECKS.map(key=>({key,passed:true,message:'Synthetic validation'}))};
const rows=[{source_row:2,location:'Cheshire',basis:'program_reported_month',measures:{cash_program_income:0}}];
async function setup(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select null::uuid$$;create function auth.jwt() returns jsonb language sql as $$select '{}'::jsonb$$;create table public.cheshire_portal_member(email text primary key);create table storage.buckets(id text primary key,name text,public boolean,file_size_limit integer,allowed_mime_types text[]);create table storage.objects(id uuid,name text,bucket_id text);alter table storage.objects enable row level security;create function storage.foldername(name text) returns text[] language sql as $$select string_to_array(name,'/')$$;`);
for(const name of ['20261001143404_cheshire_finance_snapshots.sql','20261001152657_cheshire_monthly_intake.sql','20261001154744_cheshire_fixed_monthly_basis.sql','20261001163000_cheshire_validated_metrics.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261001194828_cheshire_checklist_review_freshness.sql',import.meta.url),'utf8'));
await db.query(`insert into cheshire_intake_document(id,source_type,requested_month,reported_month,uploaded_by,file_name,content_sha256,byte_size,mime_type,storage_path,no_phi_attested_at,status,review_token,validation,review_revision) values($1,'coverage_manifest','2026-09-01','2026-09-01',$1,'Synthetic manifest.csv',$3,1,'text/csv','synthetic/manifest.csv',now(),'complete',$2,$4,$5)`,[manifestId,manifestToken,hash,JSON.stringify(review),manifestRevision]);
await db.query(`insert into cheshire_intake_document(id,source_type,requested_month,uploaded_by,file_name,content_sha256,byte_size,mime_type,storage_path,no_phi_attested_at,status,review_token) values($1,'cash_programs','2026-09-01',$1,'Synthetic upload.csv',$3,1,'text/csv','synthetic/upload.csv',now(),'reviewing',$2)`,[id,token,hash]);return db;}
const call=(db,changes={})=>{const p={id,hash,token,review,scope:null,dependencies:{coverage_manifest:`${manifestId}:${hash}`},revisions:{coverage_manifest:manifestToken},version:'cheshire-metrics-v1',rows,issue:null,...changes};return db.query('select * from finalize_cheshire_intake_review($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[p.id,p.hash,p.token,JSON.stringify(p.review),p.scope,JSON.stringify(p.dependencies),JSON.stringify(p.revisions),p.version,JSON.stringify(p.rows),p.issue]);};
test('schema and RPCs are service-only, transaction commits source and metrics once, read excludes stale reviews',async()=>{const db=await setup();try{
 const access=(await db.query(`select has_table_privilege('anon','cheshire_intake_metric_batch','select') anon_read,has_table_privilege('authenticated','cheshire_intake_metric_batch','select') member_read,has_table_privilege('service_role','cheshire_intake_metric_batch','select') service_read,has_function_privilege('authenticated','read_cheshire_metric_state(date)','execute') member_rpc,has_function_privilege('anon','finalize_cheshire_intake_review(uuid,text,uuid,jsonb,jsonb,jsonb,jsonb,text,jsonb,text)','execute') anon_write;`)).rows[0];assert.deepEqual(access,{anon_read:false,member_read:false,service_read:true,member_rpc:false,anon_write:false});
 await db.exec('set role authenticated');await assert.rejects(db.query('select * from cheshire_intake_metric_batch'),/permission denied/);await assert.rejects(db.query("select read_cheshire_metric_state('2026-09-01')"),/permission denied/);await db.exec('reset role;set role service_role');
 assert.equal((await call(db)).rows[0].status,'complete');let snapshot=(await db.query("select read_cheshire_metric_state('2026-09-01') as state")).rows[0].state;assert.equal(snapshot.batches.length,1);assert.equal(snapshot.batches[0].content_sha256,hash);assert.equal(snapshot.batches[0].review_token,token);assert.equal(snapshot.batches[0].rows[0].measures.cash_program_income,0);assert.equal((await call(db)).rows.length,0);
 await db.query("update cheshire_intake_document set status='reviewing',review_token=$2 where id=$1",[id,'66666666-6666-6666-6666-666666666666']);snapshot=(await db.query("select read_cheshire_metric_state('2026-09-01') as state")).rows[0].state;assert.equal(snapshot.batches.length,0);assert.equal((await db.query('select count(*) from cheshire_intake_metric_batch')).rows[0].count,1);
 }finally{await db.close();}});
test('stale nonce/hash, failed gates and changed dependency cannot publish facts or complete review',async()=>{const db=await setup();try{
 assert.equal((await call(db,{token:'77777777-7777-7777-7777-777777777777'})).rows.length,0);assert.equal((await call(db,{hash:'f'.repeat(64)})).rows.length,0);
 for(const changes of [{review:{...review,reference_basis:'fixed_monthly_baseline'}},{review:{...review,checks:review.checks.slice(1)}},{review:{...review,checks:review.checks.map((r,i)=>i?r:{...r,passed:false})}},{review:{...review,row_count:2}},{review:{...review,status:'incomplete'}},{revisions:{}},{revisions:{coverage_manifest:'88888888-8888-8888-8888-888888888888'}},{version:'future-version'},{issue:'currency_confirmation'}]){await assert.rejects(call(db,changes));assert.equal((await db.query('select status from cheshire_intake_document where id=$1',[id])).rows[0].status,'reviewing');assert.equal((await db.query('select count(*) from cheshire_intake_metric_batch')).rows[0].count,0);}
 // Force the final INSERT to fail after UPDATE; PostgreSQL must roll both changes back.
 await db.query(`insert into cheshire_intake_metric_batch(document_id,review_token,content_sha256,reporting_month,validator_version,normalizer_version,validation_dependencies,dependency_revisions,rows) values($1,$2,$3,'2026-09-01','cheshire-intake-v1','cheshire-metrics-v1','{}','{}','[]')`,[id,token,hash]);await assert.rejects(call(db),/duplicate key/);assert.equal((await db.query('select status from cheshire_intake_document where id=$1',[id])).rows[0].status,'reviewing');
 }finally{await db.close();}});
test('missing monetary currency stores a clear blocked metric version without inventing zeros',async()=>{const db=await setup();try{await call(db,{rows:[],issue:'currency_confirmation'});const batch=(await db.query('select * from cheshire_intake_metric_batch')).rows[0];assert.equal(batch.normalization_issue,'currency_confirmation');assert.deepEqual(batch.rows,[]);}finally{await db.close();}});

const checklist=async db=>{const docs=(await db.query('select to_jsonb(d) as document from cheshire_intake_document d')).rows.map(row=>row.document);return Object.fromEntries(buildMonthlyChecklist(parseIntakeDocuments(docs),'2026-09',null).map(item=>[item.id,item.status]));};
test('review versions rotate atomically on same-byte manifest re-review and checklist fails closed',async()=>{const db=await setup();try{
 const completed=(await call(db)).rows[0];assert.match(completed.review_revision,/^[a-f0-9-]{36}$/);assert.notEqual(completed.review_revision,token);assert.deepEqual(completed.validation_dependency_revisions,{coverage_manifest:manifestRevision});assert.equal((await checklist(db)).cash_programs,'complete');
 const nextToken='bbbbbbbb-1111-4111-8111-111111111111';await db.query("update cheshire_intake_document set status='reviewing',review_token=$2 where id=$1",[manifestId,nextToken]);assert.equal((await checklist(db)).cash_programs,'incomplete');
 const renewed=(await call(db,{id:manifestId,token:nextToken,dependencies:{},revisions:{},rows:[]})).rows[0];assert.notEqual(renewed.review_revision,manifestRevision);assert.notEqual(renewed.review_revision,nextToken);assert.equal(renewed.content_sha256,hash);assert.equal((await checklist(db)).coverage_manifest,'complete');assert.equal((await checklist(db)).cash_programs,'incomplete');
 const cashToken='cccccccc-1111-4111-8111-111111111111';await db.query("update cheshire_intake_document set status='reviewing',review_token=$2 where id=$1",[id,cashToken]);const current=(await call(db,{token:cashToken,revisions:{coverage_manifest:nextToken}})).rows[0];assert.notEqual(current.review_revision,completed.review_revision);assert.deepEqual(current.validation_dependency_revisions,{coverage_manifest:renewed.review_revision});assert.equal((await checklist(db)).cash_programs,'complete');
 }finally{await db.close();}});
test('allocation requires a current payroll supporting review, including transitive manifest revision',async()=>{const db=await setup();try{
 let payrollToken='eeeeeeee-1111-4111-8111-111111111111';const payrollId='dddddddd-1111-4111-8111-111111111111',allocationId='ffffffff-1111-4111-8111-111111111111',allocationToken='abababab-1111-4111-8111-111111111111';
 for(const [docId,source,reviewToken] of [[payrollId,'payroll',payrollToken],[allocationId,'staff_allocation',allocationToken]])await db.query(`insert into cheshire_intake_document(id,source_type,requested_month,uploaded_by,file_name,content_sha256,byte_size,mime_type,storage_path,no_phi_attested_at,status,review_token) values($1,$2,'2026-09-01',$1,'Synthetic dependency.csv',$4,1,'text/csv',$1::uuid::text||'/source.csv',now(),'reviewing',$3)`,[docId,source,reviewToken,hash]);
 const payroll=()=>call(db,{id:payrollId,token:payrollToken,rows:[{source_row:2,location:null,basis:'payroll_reported_month',measures:{loaded_payroll:0,paid_hours:0}}]});await payroll();
 const allocation=(manifestReview=manifestToken)=>call(db,{id:allocationId,token:allocationToken,dependencies:{coverage_manifest:`${manifestId}:${hash}`,payroll:`${payrollId}:${hash}`},revisions:{coverage_manifest:manifestReview,payroll:payrollToken},rows:[]});const first=(await allocation()).rows[0];assert.equal((await checklist(db)).staff_allocation,'complete');assert.equal((await db.query('select count(*) from cheshire_intake_metric_batch where document_id=$1',[allocationId])).rows[0].count,0,'non-metric allocation still persists revision evidence');
 const nextManifest='bcbcbcbc-1111-4111-8111-111111111111';await db.query("update cheshire_intake_document set status='reviewing',review_token=$2 where id=$1",[manifestId,nextManifest]);await call(db,{id:manifestId,token:nextManifest,dependencies:{},revisions:{},rows:[]});assert.equal((await checklist(db)).staff_allocation,'incomplete');
 await db.query("update cheshire_intake_document set status='reviewing' where id=$1",[allocationId]);await assert.rejects(allocation(nextManifest),/Payroll supporting review changed/);assert.equal((await db.query('select review_revision from cheshire_intake_document where id=$1',[allocationId])).rows[0].review_revision,first.review_revision,'rejected review cannot update safe revision');
 payrollToken='cececece-1111-4111-8111-111111111111';await db.query("update cheshire_intake_document set status='reviewing',review_token=$2 where id=$1",[payrollId,payrollToken]);await call(db,{id:payrollId,token:payrollToken,revisions:{coverage_manifest:nextManifest},rows:[]});assert.equal((await checklist(db)).payroll,'complete');await allocation(nextManifest);assert.equal((await checklist(db)).staff_allocation,'complete');
 const nextPayroll='cdcdcdcd-1111-4111-8111-111111111111';await db.query("update cheshire_intake_document set status='reviewing',review_token=$2 where id=$1",[payrollId,nextPayroll]);await call(db,{id:payrollId,token:nextPayroll,revisions:{coverage_manifest:nextManifest},rows:[]});assert.equal((await checklist(db)).payroll,'complete');assert.equal((await checklist(db)).staff_allocation,'incomplete');
 }finally{await db.close();}});
test('legacy supporting reviews without safe versions cannot establish completion',async()=>{const db=await setup();try{await db.query('update cheshire_intake_document set review_revision=null where id=$1',[manifestId]);await assert.rejects(call(db),/Supporting review version unavailable/);assert.equal((await checklist(db)).coverage_manifest,'incomplete');}finally{await db.close();}});
