import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,rm}from'node:fs/promises';import{fileURLToPath,pathToFileURL}from'node:url';import{build}from'esbuild';import React from'react';import{create,act}from'react-test-renderer';
test('summary starts collapsed, has one generic uploader, changes real period/scope and closes old-month upload state',async()=>{
 const cache=fileURLToPath(new URL('../node_modules/.cache/',import.meta.url));await mkdir(cache,{recursive:true});const dir=await mkdtemp(cache+'summary-ui-');let renderer;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
 try{await build({stdin:{contents:`import React from'react';import{IntakeContext}from'./src/cheshire/intakeContext';import{CheshireFinanceDashboardView}from'./src/cheshire/CheshireFinanceDashboardView';export function Harness({month='2026-10',busy=false,state='ready'}){const value={month,busy,state,selected:'coverage_manifest',documents:[],referenceSnapshot:null,setMonth:()=>{},setSelected:()=>{},refresh:()=>{}};return <IntakeContext.Provider value={value}><CheshireFinanceDashboardView snapshot={null} state="empty" onRefresh={()=>{}}/></IntakeContext.Provider>}`,resolveDir:fileURLToPath(new URL('../',import.meta.url)),loader:'tsx'},outfile:dir+'/ui.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'},define:{'import.meta.env':'{}'},logLevel:'silent',plugins:[{name:'controlled-period-and-upload',setup(b){b.onResolve({filter:/useProfitabilityPeriod$/},()=>({path:'period',namespace:'mock'}));b.onLoad({filter:/period/,namespace:'mock'},()=>({contents:`import{useIntake}from'${fileURLToPath(new URL('../src/cheshire/intakeContext.ts',import.meta.url))}';import{reportingMonths}from'${fileURLToPath(new URL('../src/cheshire/periodSummary.ts',import.meta.url))}';export function useProfitabilityPeriod(mode,scope){const i=useIntake();return{months:reportingMonths(mode,i.month),scope,responses:{},categories:[],failedMonths:[],mapError:false,state:i.state==='ready'&&!i.busy?'ready':'waiting'}}`,loader:'ts',resolveDir:fileURLToPath(new URL('../',import.meta.url))}));b.onResolve({filter:/CheshireReportUpload$/},()=>({path:'upload',namespace:'mock'}));b.onLoad({filter:/upload/,namespace:'mock'},()=>({contents:`import React from'react';export function CheshireReportUpload(props){return <div data-test="upload" data-source={props.source??'auto'}><button onClick={props.onClose}>Close</button></div>}`,loader:'tsx',resolveDir:fileURLToPath(new URL('../',import.meta.url))}));}}]});
 const{Harness}=await import(pathToFileURL(dir+'/ui.mjs'));await act(async()=>{renderer=create(React.createElement(Harness,{}));});
 const buttons=()=>renderer.root.findAllByType('button');const upload=()=>buttons().find(b=>b.props.className==='csd-upload');assert.equal(buttons().filter(b=>String(b.props.className??'').includes('upload')).length,1);assert.equal(renderer.root.findAllByProps({className:'cfi-generic-upload'}).length,0);
 const categories=renderer.root.findAllByType('details').filter(item=>String(item.props.className).startsWith('csd-category '));assert.equal(categories.length,5);assert.ok(categories.every(item=>!item.props.open));
 const totals=renderer.root.findByProps({className:'csd-totals'}).findAllByType('strong');assert.deepEqual(totals.map(node=>node.children.join('')),['Missing','Missing','Missing']);
 await act(async()=>upload().props.onClick());assert.equal(renderer.root.findByProps({'data-test':'upload'}).props['data-source'],'auto');await act(async()=>renderer.update(React.createElement(Harness,{month:'2026-09'})));assert.equal(renderer.root.findAllByProps({'data-test':'upload'}).length,0);
 const ytd=buttons().find(button=>button.children.join('')==='YTD');await act(async()=>ytd.props.onClick());assert.equal(ytd.props['aria-pressed'],true);assert.ok(JSON.stringify(renderer.toJSON()).includes('Jan–Sep 2026'));
 await act(async()=>renderer.root.findByProps({'aria-label':'Location'}).props.onChange({target:{value:'Pool'}}));assert.equal(renderer.root.findByProps({className:'csd-period-context'}).findByType('strong').children.join(''),'YTD · Jan–Sep 2026 · Pool');
 await act(async()=>renderer.update(React.createElement(Harness,{month:'2026-09',busy:true})));assert.equal(upload().props.disabled,true);assert.equal(renderer.root.findByProps({className:'csd-totals'}).findAllByType('strong')[0].children.join(''),'Checking');
 }finally{if(renderer)await act(async()=>renderer.unmount());await rm(dir,{recursive:true,force:true});delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
});
