import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';import {fileURLToPath,pathToFileURL} from 'node:url';import {build} from 'esbuild';
import React from 'react';import {create,act} from 'react-test-renderer';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const cache=fileURLToPath(new URL('../node_modules/.cache/',import.meta.url));await mkdir(cache,{recursive:true});const dir=await mkdtemp(cache+'mapping-ui-');
await build({stdin:{contents:`export {CheshireReportUpload} from './src/cheshire/CheshireReportUpload';export {IntakeContext} from './src/cheshire/intakeContext';`,resolveDir:fileURLToPath(new URL('../',import.meta.url)),loader:'tsx'},outfile:dir+'/harness.mjs',bundle:true,packages:'external',platform:'node',format:'esm',jsx:'automatic',loader:{'.css':'empty'},logLevel:'silent'});
const {CheshireReportUpload,IntakeContext}=await import(pathToFileURL(dir+'/harness.mjs'));
const text='Cycle,office,program,income,report_total,currency\n2026-09,Cheshire,synthetic,1,1,USD';const bytes=new TextEncoder().encode(text);
const file=(name='synthetic.csv',data=bytes)=>({name,size:data.length,arrayBuffer:async()=>data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength)});
const flush=()=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,15))});
const savedDocument=globalThis.document;globalThis.document={activeElement:{focus(){}},getElementById(){return null;}};
function base(extra={}){return {month:'2026-09',documents:[],state:'ready',aiEnabled:false,mappingEnabled:true,busy:false,message:'',upload:async()=>false,suggestReportType:async()=>({source_types:[],ai_status:'unavailable'}),...extra};}
async function harness(context=base(),props={source:'cash_programs'}){let renderer;await act(async()=>{renderer=create(React.createElement(IntakeContext.Provider,{value:context},React.createElement(CheshireReportUpload,{...props,onClose:context.close??(()=>{})})),{createNodeMock:()=>({focus(){},querySelectorAll(){return[];}})});});return renderer;}
const input=(r,label)=>r.root.findByProps({'aria-label':label});const submit=r=>r.root.findByProps({type:'submit'});const choose=async(r,f)=>{await act(async()=>input(r,'Choose monthly source file').props.onChange({target:{files:f?[f]:[]}}));await flush();};
const check=async(r)=>{await act(async()=>{r.root.findAllByProps({type:'checkbox'})[0].props.onChange({target:{checked:true}});input(r,'Confirm report mapping').props.onChange({target:{checked:true}});});};
try{
 await test('confirm then edit invalidates confirmation; submit preserves original bytes and mapping and prevents repeat clicks',async()=>{let calls=[],resolve,closed=0;const r=await harness(base({upload:(...args)=>{calls.push(args);return new Promise(r=>resolve=r);},close:()=>closed++}));try{await choose(r,file());assert.equal(submit(r).props.disabled,true);assert.equal(input(r,'Map source column 1').props.value,'');await check(r);assert.equal(submit(r).props.disabled,false);await act(async()=>input(r,'Map source column 1').props.onChange({target:{value:'reporting_month'}}));assert.equal(input(r,'Confirm report mapping').props.checked,false);assert.equal(submit(r).props.disabled,true);await check(r);await act(async()=>{const handler=r.root.findByType('form').props.onSubmit;void handler({preventDefault(){}});void handler({preventDefault(){}});});assert.equal(calls.length,1);assert.equal(calls[0][0].name,'synthetic.csv');assert.equal(calls[0][3].columns[0],'reporting_month');assert.equal(calls[0][3].source_sha256.length,64);await act(async()=>resolve(true));assert.equal(closed,1);}finally{await act(async()=>r.unmount());}});
 await test('new file clears confirmation and stale earlier inspection cannot replace its preview',async()=>{let release;const old={name:'old.csv',size:bytes.length,arrayBuffer:()=>new Promise(r=>release=r)};const r=await harness();try{await act(async()=>input(r,'Choose monthly source file').props.onChange({target:{files:[old]}}));await choose(r,file('new.csv'));await check(r);await act(async()=>release(bytes.buffer));await flush();assert.equal(input(r,'Confirm report mapping').props.checked,true);assert(JSON.stringify(r.toJSON()).includes('new.csv'));await choose(r,null);assert.equal(input(r,'Confirm report mapping').props.checked,false);assert.equal(submit(r).props.disabled,true);}finally{await act(async()=>r.unmount());}});
 await test('AI late response cannot apply to a newer file, override category or grant confirmation',async()=>{const resolves=[];const r=await harness(base({aiEnabled:true,suggestReportType:()=>new Promise(resolve=>resolves.push(resolve))}));try{await choose(r,file('first.csv'));await choose(r,file('second.csv'));await act(async()=>resolves[0]({source_types:['payroll'],ai_status:'assisted'}));assert(!JSON.stringify(r.toJSON()).includes('AI report-type hint: Payroll'));await act(async()=>resolves[1]({source_types:['cash_programs'],ai_status:'assisted'}));assert.equal(input(r,'Report type').props.value,'cash_programs');assert.equal(input(r,'Confirm report mapping').props.checked,false);assert(JSON.stringify(r.toJSON()).includes('AI report-type hint: Cash programs'));}finally{await act(async()=>r.unmount());}});
 await test('blocked identifiers and service-version mismatch prevent upload',async()=>{for(const [context,sourceFile] of [[base(),file('restricted.csv',new TextEncoder().encode('patient_name,income\nSYNTHETIC,1'))],[base({mappingEnabled:false}),file()]]){const r=await harness(context);try{await choose(r,sourceFile);await check(r);assert.equal(submit(r).props.disabled,true);}finally{await act(async()=>r.unmount());}}});
 await test('generic intake requires chosen report type and changing it clears replacements and confirmation',async()=>{const r=await harness(base(),{});try{await choose(r,file());assert.equal(input(r,'Report type').props.value,'');assert.equal(submit(r).props.disabled,true);await act(async()=>input(r,'Report type').props.onChange({target:{value:'cash_programs'}}));await check(r);assert.equal(submit(r).props.disabled,false);await act(async()=>input(r,'Report type').props.onChange({target:{value:'payroll'}}));assert.equal(input(r,'Confirm report mapping').props.checked,false);assert.equal(submit(r).props.disabled,true);}finally{await act(async()=>r.unmount());}});
 await test('unmount during inspection ignores completion; failed upload leaves source available for retry',async()=>{let resolve;const pending={name:'pending.csv',size:bytes.length,arrayBuffer:()=>new Promise(r=>resolve=r)};const r=await harness();await act(async()=>input(r,'Choose monthly source file').props.onChange({target:{files:[pending]}}));await act(async()=>r.unmount());await act(async()=>resolve(bytes.buffer));await flush();let count=0,closed=0;const retry=await harness(base({upload:async()=>{count++;return false;},close:()=>closed++}));try{await choose(retry,file());await check(retry);await act(async()=>retry.root.findByType('form').props.onSubmit({preventDefault(){}}));await act(async()=>retry.root.findByType('form').props.onSubmit({preventDefault(){}}));assert.equal(count,2);assert.equal(closed,0);assert.equal(input(retry,'Confirm report mapping').props.checked,true);}finally{await act(async()=>retry.unmount());}});
}finally{globalThis.document=savedDocument;await rm(dir,{recursive:true,force:true});}
