import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,rm}from'node:fs/promises';import{fileURLToPath,pathToFileURL}from'node:url';import{build}from'esbuild';import React from'react';import{create,act}from'react-test-renderer';
test('brand location picker supports all locations, keyboard selection/typeahead, dismissal and focus return',async()=>{
 const cache=fileURLToPath(new URL('../node_modules/.cache/',import.meta.url));await mkdir(cache,{recursive:true});const dir=await mkdtemp(cache+'location-picker-');let renderer;const oldDocument=globalThis.document,oldNode=globalThis.Node;const listeners=new Map();let triggerFocus=0,listFocus=0;globalThis.IS_REACT_ACT_ENVIRONMENT=true;globalThis.Node=class{};const inside=new globalThis.Node();globalThis.document={addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:(name,fn)=>{if(listeners.get(name)===fn)listeners.delete(name)}};
 try{await build({stdin:{contents:`import React,{useState}from'react';import{CheshireLocationPicker}from'./src/cheshire/CheshireLocationPicker';export function Harness(){const[value,setValue]=useState('all');return <CheshireLocationPicker value={value} onChange={setValue}/>}`,resolveDir:fileURLToPath(new URL('../',import.meta.url)),loader:'tsx'},outfile:dir+'/test.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',logLevel:'silent'});const{Harness}=await import(pathToFileURL(dir+'/test.mjs'));await act(async()=>{renderer=create(React.createElement(Harness),{createNodeMock:element=>element.type==='button'?{focus:()=>triggerFocus++}:element.type==='ul'?{focus:()=>listFocus++}:element.type==='div'?{contains:target=>target===inside}:null});});
 const trigger=()=>renderer.root.findByType('button');const menu=()=>renderer.root.findByProps({role:'listbox'});const key=async(key)=>{let prevented=false;await act(async()=>menu().props.onKeyDown({key,preventDefault(){prevented=true}}));return prevented};const selected=()=>renderer.root.findAllByProps({role:'option'}).filter(option=>option.props['aria-selected']).map(option=>option.findByType('span').children.join(''));
 await act(async()=>trigger().props.onKeyDown({key:'ArrowDown',preventDefault(){}}));assert.equal(trigger().props['aria-expanded'],true);assert.ok(listFocus>0);assert.deepEqual(renderer.root.findAllByProps({role:'option'}).map(option=>option.findByType('span').children.join('')),['All locations','Cheshire','Cromwell','Guilford','Meriden','Orange','Pool','Torrington']);assert.deepEqual(selected(),['All locations']);
 let mouseFocusPrevented=false;const pool=renderer.root.findAllByProps({role:'option'}).find(option=>option.findByType('span').children.join('')==='Pool');pool.props.onMouseDown({preventDefault(){mouseFocusPrevented=true}});assert.equal(mouseFocusPrevented,true,'option mousedown must retain listbox focus until click selects');await act(async()=>pool.props.onClick());assert.equal(trigger().findByType('span').children.join(''),'Pool');await act(async()=>trigger().props.onClick());
 await key('End');assert.match(menu().props['aria-activedescendant'],/-7$/);await key('Home');assert.match(menu().props['aria-activedescendant'],/-0$/);await key('ArrowUp');assert.match(menu().props['aria-activedescendant'],/-7$/);await key('g');assert.match(menu().props['aria-activedescendant'],/-3$/);await key('Enter');assert.equal(trigger().findByType('span').children.join(''),'Guilford');assert.equal(trigger().props['aria-expanded'],false);assert.ok(triggerFocus>0);assert.equal(listeners.size,0);
 await act(async()=>trigger().props.onClick());assert.deepEqual(selected(),['Guilford']);await key('ArrowDown');await key('Escape');assert.equal(trigger().findByType('span').children.join(''),'Guilford');assert.equal(trigger().props['aria-expanded'],false);
 await act(async()=>trigger().props.onClick());await key('c');assert.match(menu().props['aria-activedescendant'],/-1$/);await key('c');assert.match(menu().props['aria-activedescendant'],/-2$/);await key(' ');assert.equal(trigger().findByType('span').children.join(''),'Cromwell');
 await act(async()=>trigger().props.onClick());await act(async()=>listeners.get('pointerdown')({target:inside}));assert.equal(trigger().props['aria-expanded'],true);await act(async()=>listeners.get('pointerdown')({target:new globalThis.Node()}));assert.equal(trigger().props['aria-expanded'],false);
 await act(async()=>trigger().props.onClick());assert.equal(await key('Tab'),false);assert.equal(trigger().props['aria-expanded'],false);
 }finally{if(renderer)await act(async()=>renderer.unmount());await rm(dir,{recursive:true,force:true});if(oldDocument===undefined)delete globalThis.document;else globalThis.document=oldDocument;if(oldNode===undefined)delete globalThis.Node;else globalThis.Node=oldNode;delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
});
