import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,rm}from'node:fs/promises';import{fileURLToPath,pathToFileURL}from'node:url';import{build}from'esbuild';import React from'react';import{create,act}from'react-test-renderer';
test('cell uploads identify their exact location/category, disable safely, and groups preserve table rows',async()=>{
 const cache=fileURLToPath(new URL('../node_modules/.cache/',import.meta.url));await mkdir(cache,{recursive:true});const dir=await mkdtemp(cache+'sheet-ui-');let renderer;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
 try{await build({entryPoints:[fileURLToPath(new URL('../src/cheshire/CheshireProfitabilitySheet.tsx',import.meta.url))],outfile:dir+'/sheet.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'},logLevel:'silent'});const{CheshireProfitabilitySheet}=await import(pathToFileURL(dir+'/sheet.mjs'));const calls=[];const scroller={scrollLeft:800};const props={snapshot:null,metrics:{},categories:[],location:'all',canUpload:true,onUpload:(...args)=>calls.push(args)};
 await act(async()=>{renderer=create(React.createElement(CheshireProfitabilitySheet,props),{createNodeMock:element=>element.props.className==='cps-scroll'?scroller:null});});
 const trigger=renderer.root.findByProps({'aria-label':'Upload Insurance payments · Cromwell'});await act(async()=>trigger.props.onClick());assert.deepEqual(calls,[['insurance_revenue','Insurance payments · Cromwell']]);
 const header=renderer.root.findAllByType('button').find(button=>button.props['aria-controls']==='cps-rows-revenue');assert.equal(header.props['aria-expanded'],true);await act(async()=>header.props.onClick());assert.equal(renderer.root.findByProps({id:'cps-rows-revenue'}).props.hidden,true);await act(async()=>header.props.onClick());assert.equal(renderer.root.findByProps({id:'cps-rows-revenue'}).props.hidden,false);
 scroller.scrollLeft=700;await act(async()=>renderer.update(React.createElement(CheshireProfitabilitySheet,{...props,location:'Cromwell',canUpload:false})));assert.equal(scroller.scrollLeft,0);assert.equal(renderer.root.findByProps({'aria-label':'Upload Insurance payments · Cromwell'}).props.disabled,true);assert.equal(renderer.root.findAllByProps({'aria-label':'Upload Insurance payments · Cheshire'}).length,0);assert.equal(renderer.root.findAllByProps({'aria-label':'Upload Insurance payments · all-source subtotal'}).length,1);
 }finally{if(renderer)await act(async()=>renderer.unmount());await rm(dir,{recursive:true,force:true});delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
});
