import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {build} from 'esbuild';
import React from 'react';
import {create,act} from 'react-test-renderer';
import {METRICS} from '../supabase/functions/_shared/cheshire-metrics.ts';
const payload=(month='2026-09',location='all',value=123)=>({month,location,sources:[{document_id:'synthetic-doc',content_sha256:'a'.repeat(64),validator_version:'cheshire-intake-v1',normalizer_version:'cheshire-metrics-v1',source_type:'cash_programs',coverage:'validated_source_scope',location_coverage:['Cheshire'],metrics:[{key:'cash_program_income',...METRICS.cash_program_income,value,basis:'program_reported_month',location:location==='all'?null:location,source_locations:[location==='all'?'Cheshire':location],source_rows:1}]}],blocked:[],profit:{available:false,reason:'Accounting basis missing'},accounting_request:'Confirm accounting basis'});
test('month/location/review/identity changes hide old figures; late and malformed responses never restore them',async()=>{const cache=fileURLToPath(new URL('../node_modules/.cache/',import.meta.url));await mkdir(cache,{recursive:true});const dir=await mkdtemp(cache+'metric-lifecycle-');globalThis.IS_REACT_ACT_ENVIRONMENT=true;let renderer;const requests=[];globalThis.__metricInvoke=(_name,options)=>new Promise(resolve=>requests.push({options,resolve}));
 try{await build({stdin:{contents:`import React from 'react';import {IntakeContext} from './src/cheshire/intakeContext';import {useValidatedMetrics} from './src/cheshire/useValidatedMetrics';function Read({location}){const result=useValidatedMetrics(location);return <pre>{JSON.stringify(result)}</pre>;}export function Harness({month,location='all',state='ready',busy=false,actor='one',documents=[]}){return <IntakeContext.Provider key={actor} value={{month,state,busy,documents,referenceSnapshot:null}}><Read location={location}/></IntakeContext.Provider>;}`,loader:'tsx',resolveDir:fileURLToPath(new URL('../',import.meta.url))},outfile:dir+'/harness.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',plugins:[{name:'synthetic-private-client',setup(b){b.onResolve({filter:/cheshireSupabase$/},()=>({path:'mock-client',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const cheshireSupabase={functions:{invoke:(...args)=>globalThis.__metricInvoke(...args)}};',loader:'js'}));}}],logLevel:'silent'});const {Harness}=await import(pathToFileURL(dir+'/harness.mjs'));const read=()=>JSON.parse(renderer.toJSON().children[0]);const update=async props=>{await act(async()=>{renderer.update(React.createElement(Harness,props))})};const finish=async(index,result)=>{await act(async()=>{requests[index].resolve({data:{metrics:result},error:null})})};
  await act(async()=>{renderer=create(React.createElement(Harness,{month:'2026-09'}))});assert.equal(read().data,null);await finish(0,payload());assert.equal(read().data.sources[0].metrics[0].value,123);
  await update({month:'2026-10'});assert.equal(read().data,null);await update({month:'2026-10',location:'Pool'});assert.equal(read().data,null);await finish(1,payload('2026-10','all',999));assert.equal(read().data,null);await finish(2,payload('2026-10','Pool',456));assert.equal(read().data.sources[0].metrics[0].value,456);
  await update({month:'2026-10',location:'Pool',busy:true});assert.equal(read().data,null);assert.equal(read().state,'waiting');await update({month:'2026-10',location:'Pool'});assert.equal(read().data,null,'ending a failed review must not resurface the prior cached result');await finish(3,payload('2026-10','Pool',500));assert.equal(read().data.sources[0].metrics[0].value,500);await update({month:'2026-10',location:'Pool',documents:[{id:'new-source',status:'reviewing'}]});assert.equal(read().data,null);
  await update({month:'2026-10',location:'Pool',actor:'two',state:'no-access'});assert.equal(read().data,null);await finish(4,payload('2026-10','Pool',777));assert.equal(read().data,null);
  await update({month:'2026-10',location:'Pool',actor:'two'});await finish(5,payload('2026-09','Pool',888));assert.equal(read().state,'error');assert.equal(read().data,null);
 }finally{if(renderer)await act(async()=>renderer.unmount());await rm(dir,{recursive:true,force:true});delete globalThis.__metricInvoke;delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
});
