import type { ScreenDefinition } from "./types";

const money: ScreenDefinition["metrics"] = [
  { label: "Needs action", value: "$84.2k", detail: "Revenue currently blocked", tone: "attention" },
  { label: "On track", value: "91%", detail: "Against this month's plan", tone: "positive" },
  { label: "At risk", value: "$38.6k", detail: "Unsigned school services", tone: "warning" },
  { label: "Owner decisions", value: "7", detail: "Items only you can clear", tone: "error" },
];

const clinical: ScreenDefinition["metrics"] = [
  { label: "Visits today", value: "86", detail: "Across all six locations", tone: "positive" },
  { label: "Open capacity", value: "11", detail: "$1,540 in unfilled time", tone: "warning" },
  { label: "Auth risk", value: "8", detail: "Visits need verification", tone: "attention" },
  { label: "Notes due", value: "14", detail: "$2,310 cannot bill yet", tone: "error" },
];

const ops: ScreenDefinition["metrics"] = [
  { label: "Open work", value: "23", detail: "Ordered by dollars blocked", tone: "attention" },
  { label: "Healthy", value: "94%", detail: "Operational checks passing", tone: "positive" },
  { label: "Due this week", value: "9", detail: "Credentials and filings", tone: "warning" },
  { label: "Blocking", value: "3", detail: "Requires an owner decision", tone: "error" },
];

const growth: ScreenDefinition["metrics"] = [
  { label: "New referrals", value: "47", detail: "Up 12% from last month", tone: "positive" },
  { label: "Unscheduled", value: "18", detail: "$21.4k potential monthly value", tone: "attention" },
  { label: "Waitlist", value: "31", detail: "Average wait is 8.2 days", tone: "warning" },
  { label: "Conversion", value: "72%", detail: "Goal is 78%", tone: "info" },
];

const rows = [
  ["Eligibility follow-up", "Cheshire", "$12,840", "Needs action"],
  ["Unsigned service logs", "West Hartford Schools", "$9,620", "At risk"],
  ["Documentation queue", "Clinical team", "$7,490", "Blocking"],
  ["Open capacity", "Pool Location", "$4,180", "Available"],
  ["Credential renewal", "Maya Thompson, OT", "$2,340", "Due soon"],
];

const make = (
  id: string,
  path: string,
  title: string,
  eyebrow: string,
  action: string,
  kind: "money" | "clinical" | "ops" | "growth" = "ops",
  insight?: string,
): ScreenDefinition => ({
  id, path, title, eyebrow, action,
  metrics: kind === "money" ? money : kind === "clinical" ? clinical : kind === "growth" ? growth : ops,
  columns: ["Priority", "Owner / location", "Value", "Status"],
  rows,
  insight: insight ?? `${title} is ordered by business impact so the team can act on the work that protects care quality and cash first.`,
});

export const screens: ScreenDefinition[] = [
  make("dashboard", "/", "Good morning, Amy", "Tuesday, July 28", "Review owner brief", "money", "This is your daily triage—not a chart wall. Every number ties to money and a next action."),
  make("schedule", "/schedule", "Schedule", "Run the day", "New appointment", "clinical"),
  make("patientList", "/patients", "Patients", "Clinical", "New patient", "clinical"),
  make("patients", "/patients/jordan-lee", "Jordan Lee", "Patient chart", "New note", "clinical"),
  make("episode", "/patients/jordan-lee/episode", "Episode of care", "Jordan Lee", "Edit episode", "clinical"),
  make("history", "/patients/jordan-lee/history", "History & safety", "Jordan Lee", "Add precaution", "clinical"),
  make("auths", "/patients/jordan-lee/authorizations", "Eligibility & authorizations", "Jordan Lee", "Run eligibility", "clinical"),
  make("ptledger", "/patients/jordan-lee/balance", "Patient balance", "Jordan Lee", "Record payment", "money"),
  make("privacy", "/patients/jordan-lee/consents", "Consents & access", "Jordan Lee", "Request consent", "ops"),
  make("note", "/patients/jordan-lee/notes/new", "SOAP note", "Jordan Lee · PT", "Sign note", "clinical"),
  make("appt", "/appointments/apt-1042", "Appointment detail", "Jordan Lee", "Check in", "clinical"),
  make("newAppt", "/appointments/new", "New appointment", "Scheduling", "Book appointment", "clinical"),
  make("newPatient", "/patients/new", "New patient", "Intake", "Create patient", "growth"),
  make("tasks", "/tasks", "Work queue", "Run the day", "Add task", "ops"),
  make("team", "/team", "Team", "People", "Add team member", "ops"),
  make("staff", "/team/maya-thompson", "Maya Thompson, OTR/L", "Staff detail", "Edit staff", "ops"),
  make("labor", "/team/workforce", "Workforce & payroll", "People", "Run payroll", "money"),
  make("profile", "/profile", "My profile", "Amy Cahill", "Edit profile", "ops"),
  make("billing", "/billing", "Billing & claims", "Revenue cycle", "Create claim batch", "money"),
  make("claim", "/billing/claims/CLM-10492", "Claim CLM-10492", "Claim detail", "Resubmit claim", "money"),
  make("reimburse", "/reimbursements", "Insurance reimbursements", "Revenue cycle", "Post remittance", "money"),
  make("era", "/reimbursements/ERA-3821", "Remittance ERA-3821", "Insurance payment", "Post ERA", "money"),
  make("appeal", "/billing/appeals/APL-228", "Appeal packet", "Denied claim", "Send appeal", "money"),
  make("payers", "/payers", "Payers", "Revenue cycle", "Add payer", "money"),
  make("payer", "/payers/aetna", "Aetna", "Payer detail", "Edit contract", "money"),
  make("pipeline", "/billing/submission-pipeline", "Submission pipeline", "EDI", "Submit batch", "money"),
  make("enrollment", "/billing/edi-enrollments", "EDI enrollments", "EDI", "New enrollment", "ops"),
  make("reports", "/financials", "Financials", "Operating view", "Export report", "money"),
  make("pnl", "/financials/pnl-by-location", "P&L by location", "Financials", "Export P&L", "money"),
  make("brief", "/financials/owner-brief", "Weekly owner brief", "Financials", "Share brief", "money"),
  make("accounting", "/accounting", "Accounting", "Books & cash", "Review close", "money"),
  make("coa", "/accounting/chart-of-accounts", "Chart of accounts", "Accounting", "Add account", "money"),
  make("je", "/accounting/journal-entries/new", "Journal entry", "Accounting", "Post entry", "money"),
  make("ledger", "/accounting/general-ledger", "General ledger & close", "Accounting", "Start close", "money"),
  make("accountant", "/accounting/accountant-access", "Accountant access & audit", "Accounting", "Invite accountant", "ops"),
  make("ap", "/accounting/bills", "Bills & AP", "Accounting", "Add bill", "money"),
  make("bill", "/accounting/bills/BILL-2088", "Bill BILL-2088", "Accounts payable", "Approve bill", "money"),
  make("payrun", "/accounting/pay-runs/new", "Pay run", "Accounts payable", "Release payments", "money"),
  make("vendors", "/accounting/vendors", "Vendors & 1099", "Accounting", "Add vendor", "money"),
  make("expenses", "/accounting/expenses", "Expenses & receipts", "Accounting", "Add expense", "money"),
  make("banking", "/accounting/banking", "Bank & card feeds", "Accounting", "Match selected", "money"),
  make("recon", "/accounting/reconciliation", "Reconciliation", "Accounting", "Finish reconciliation", "money"),
  make("statements", "/accounting/statements/profit-and-loss", "Statements · Profit & loss", "Accounting", "Export statement", "money"),
  make("balanceSheet", "/accounting/statements/balance-sheet", "Statements · Balance sheet", "Accounting", "Export statement", "money"),
  make("cashFlow", "/accounting/statements/cash-flow", "Statements · Cash flow", "Accounting", "Export statement", "money"),
  make("budgets", "/accounting/budgets", "Budget vs actual", "Accounting", "Edit budget", "money"),
  make("depreciation", "/accounting/fixed-assets", "Fixed assets & depreciation", "Accounting", "Add asset", "money"),
  make("taxes", "/accounting/tax-filings", "Tax & filings", "Accounting", "Add filing", "money"),
  make("payrolltax", "/accounting/payroll-tax", "Payroll tax & year-end", "Accounting", "Resolve notice", "money"),
  make("referrals", "/referrals", "Referrals & intake", "Grow", "New referral", "growth"),
  make("referral", "/referrals/REF-1048", "Referral REF-1048", "Intake detail", "Schedule evaluation", "growth"),
  make("growth", "/growth", "Growth engine", "Grow", "New campaign", "growth"),
  make("providers", "/referring-providers", "Referring providers", "Grow", "Add provider", "growth"),
  make("waitlist", "/waitlist", "Waitlist", "Grow", "Offer opening", "growth"),
  make("locations", "/locations", "Locations", "Operations", "Add location", "money"),
  make("location", "/locations/cheshire", "Cheshire", "Location detail", "Edit location", "money"),
  make("schools", "/schools", "Schools & districts", "Operations", "New contract", "money"),
  make("schoolContract", "/schools/west-hartford", "West Hartford Public Schools", "School contract", "Log service", "money"),
  make("newContract1", "/schools/contracts/new/term", "New contract · District & term", "Step 1 of 5", "Continue", "money"),
  make("newContract2", "/schools/contracts/new/rates", "New contract · Rate card", "Step 2 of 5", "Continue", "money"),
  make("newContract3", "/schools/contracts/new/staffing", "New contract · Staffing", "Step 3 of 5", "Continue", "ops"),
  make("newContract4", "/schools/contracts/new/invoicing", "New contract · Invoicing", "Step 4 of 5", "Continue", "money"),
  make("newContract5", "/schools/contracts/new/review", "New contract · Review & send", "Step 5 of 5", "Send for signature", "money"),
  make("inventory", "/inventory", "Inventory", "Operations", "Adjust stock", "ops"),
  make("equipment", "/equipment", "Equipment & assets", "Operations", "Add equipment", "ops"),
  make("po", "/purchasing/orders/PO-1842", "Purchase order PO-1842", "Operations", "Send purchase order", "money"),
  make("compliance", "/compliance", "Compliance", "Risk & safety", "Add requirement", "ops"),
  make("codeset", "/compliance/code-sets", "Code sets", "Compliance", "Import version", "ops"),
  make("rule", "/compliance/scrub-rules/new", "Scrub rule builder", "Compliance", "Publish rule", "ops"),
  make("incidents", "/compliance/incidents", "Incidents & safety", "Compliance", "Report incident", "ops"),
  make("integrations", "/settings/integrations", "Integrations & vendors", "Settings", "Add integration", "ops"),
  make("settings", "/settings", "Settings", "Organization", "Save settings", "ops"),
  make("automation", "/growth/automations/AUTO-14", "Referral follow-up", "Automation detail", "Save automation", "growth"),
  make("template", "/growth/templates/TPL-8", "Message template", "Growth", "Save template", "growth"),
  make("messages", "/messages/THR-204", "Conversation with Elena Lee", "Messages", "Send message", "growth"),
  make("notifications", "/notifications", "Notifications", "Updates", "Mark all read", "ops"),
  make("search", "/search", "Search results", "All records", "Refine search", "ops"),
];

export const screenByPath = new Map(screens.map((screen) => [screen.path, screen]));
